import type { ExpansionCapability, ExpansionScope, CreatorIdentity } from "./expansion";
export interface AdvancementContext { creator: CreatorIdentity | null; localOwner: boolean; origin: string; requestId: string }
export interface ConfigSnapshot { scope: ExpansionScope; revision: number; config: Record<string, unknown> }
export interface ConfigChange { id: string; baseRevision: number; config: Record<string, unknown>; approvalFingerprint: string; expiresAt: string; appliedRevision: number | null }
export interface FeatureFlag { key: string; enabled: boolean; revision: number; ownerId: string; expiresAt: string | null; reason: string }
export interface SecurityStatus { enabled: boolean; enrolledAt: string | null; recoveryCodesRemaining: number; stepUpRequired: boolean }
export interface StepUpInput { password: string; code?: string; recoveryCode?: string; method: string; path: string; projectId?: string; environmentId?: string; payload?: unknown }
export interface ServiceIdentity { id: string; name: string; scope: ExpansionScope; capabilities: ExpansionCapability[]; ownerId: string; expiresAt: string; revoked: boolean; revision: number; lastUsedAt: string | null }
export interface SupportSession { id: string; supportId: string; approvedBy: string; capabilities: ExpansionCapability[]; reason: string; expiresAt: string; revoked: boolean; createdAt: string }
export interface AssetInspection { state: 'quarantined' | 'approved' | 'rejected'; visibility: 'private' | 'public'; revision: number; inspection: { kind: string; malwareScan: 'not-configured'; mime?: string; width?: number; height?: number; frames?:number; decodedPixels?:number; decoder?:string; metadataStripped?:boolean }; sourceRef: string | null; reason: string }
export interface BookingChangeReview {id:string;approvalFingerprint:string;affected:{slots:number;confirmed:number;offered:number;waiting:number};conflicts:string[];expiresAt:string;preservesMaterializedSlots:true;applied?:boolean}
export interface SecretVersion { id: string; name: string; environmentId: string; version: number; keyId: string; status: "registered" | "tested" | "active" | "retired"; testedAt: string | null; createdAt: string }
export interface AuditEntry { sequence: number; organizationId: string; actorId: string; operation: string; resourceId: string; status: string; beforeRevision: number | null; afterRevision: number | null; previousHash: string; hash: string; createdAt: string }
export interface AdapterCapabilities { idempotentWrites: boolean; statusLookup: boolean; cancellation: boolean; maxConcurrent: number; maxRetries: number; timeoutMs: number; cacheVisibility: "public" | "private" }
export interface WorkflowSimulation { workflowId: string; revision: number; matched: boolean; conditions: { field: string; matched: boolean }[]; actions: { index: number; type: string; connectionId?: string; fields?: string[]; configured?: boolean; effect: "simulated" }[]; externalEffects: false }
export interface FinancialEntry { id: string; realm: "orders" | "subscriptions"; projectId: string; targetId: string; kind: string; amountMinor: number; currency: string; commandId: string | null; eventId: string | null; createdAt: string }
export interface ReconciliationCase { id: string; scope: ExpansionScope; kind: "payment" | "deployment" | "work" | "restore"; targetId: string; revision: number; status: "open" | "verified" | "held"; evidence: { source: string; fingerprint: string; observedAt: string } | null; resolution: "completed" | "no-effect" | "held" | null }
export interface BackupFile { kind: "central" | "environment" | "blob"; path: string; bytes: number; sha256: string; scope?: ExpansionScope }
export interface ArtifactBackup {releaseId:string;sourceReleaseId:string;originalDirectory:string;backupDirectory:string;bytes:number;files:{path:string;sha256:string;bytes:number}[]}
export interface BackupSet { id: string; scope: ExpansionScope; state: "creating" | "verified" | "failed"; files: BackupFile[]; artifacts?:ArtifactBackup[]; keyIds: string[]; createdAt: string; verifiedAt: string | null; errorCode: string | null; consistency: "scoped-freeze" | "online-per-database" }
export interface PrivacyRequest { id: string; scope: ExpansionScope; subjectId: string; action: "export" | "anonymize"; status: "requested" | "held" | "completed"; heldReason: string | null; counts: Record<string, number>; createdAt: string }
export interface OrganizationLifecycle { organizationId: string; revision: number; state: "active" | "archived" | "closing"; reason: string; updatedAt: string }
export interface CatalogVersion { id: string; organizationId: string; packageId: string; version: string; integrity: string; status: "pending" | "approved" | "revoked"; publisherId: string; reviewerId: string | null; license: string; supportContact: string; evidence: string; createdAt: string }
