import { randomUUID } from "node:crypto";
import type { DatabaseSync } from "node:sqlite";
import type { AdapterCapabilities } from "../../src/domain/advancement";
import type { Connection, Transport } from "../platform/connections";
import { HttpError } from "../http";
import { boolean, integer, many, one, transaction } from "../platform/common";
import { record } from "../../src/domain/validation";
const defaults:AdapterCapabilities={idempotentWrites:false,statusLookup:false,cancellation:false,maxConcurrent:2,maxRetries:1,timeoutMs:10000,cacheVisibility:"private"};
export class AdapterPolicyService {
  constructor(readonly db:DatabaseSync){}
  list(projectId:string):Record<string,unknown>[]{return many(this.db,"SELECT c.id,c.name,p.capabilities,p.revision,p.failures,p.open_until AS openUntil FROM platform_connections c LEFT JOIN advancement_adapter_policy p ON p.connection_id=c.id WHERE c.project_id=? ORDER BY c.id",projectId).map(row=>({...row,capabilities:row.capabilities?JSON.parse(String(row.capabilities)):defaults,revision:Number(row.revision??0),failures:Number(row.failures??0)}));}
  save(projectId:string,id:string,input:Record<string,unknown>):Record<string,unknown>{if(!one(this.db,"SELECT id FROM platform_connections WHERE id=? AND project_id=?",id,projectId))throw new HttpError(404,"CONNECTION","연결을 찾을 수 없습니다.");const value=record(input.capabilities),visibility=value.cacheVisibility??"private";if(!["public","private"].includes(String(visibility)))throw new HttpError(400,"CACHE_VISIBILITY","캐시 공개 범위를 확인하세요.");const capabilities:AdapterCapabilities={idempotentWrites:boolean(value.idempotentWrites,"쓰기 멱등성",false),statusLookup:boolean(value.statusLookup,"상태 조회",false),cancellation:boolean(value.cancellation,"취소",false),maxConcurrent:integer(value.maxConcurrent??2,"동시 요청",1,10),maxRetries:integer(value.maxRetries??1,"재시도",0,3),timeoutMs:integer(value.timeoutMs??10000,"총 제한 시간",1000,10000),cacheVisibility:visibility as AdapterCapabilities["cacheVisibility"]};transaction(this.db,()=>{const previous=one(this.db,"SELECT revision FROM advancement_adapter_policy WHERE connection_id=?",id),base=integer(input.baseRevision,"연결 정책 revision");if(base!==Number(previous?.revision??0))throw new HttpError(409,"ADAPTER_CONFLICT","연결 정책이 변경되었습니다.");this.db.prepare("INSERT INTO advancement_adapter_policy VALUES(?,?,0,0,?) ON CONFLICT(connection_id) DO UPDATE SET capabilities=excluded.capabilities,revision=excluded.revision").run(id,JSON.stringify(capabilities),base+1);});return this.list(projectId).find(item=>item.id===id)!;}
}
export async function boundedProviderRequest(db:DatabaseSync,connection:Connection,method:"GET"|"POST",payload:unknown,key:string,transport:Transport):Promise<unknown>{
  if(!one(db,"SELECT name FROM sqlite_master WHERE name='advancement_adapter_policy'"))return transport(connection,method,payload,key);
  const claim=randomUUID(),started=Date.now(),row=one(db,"SELECT * FROM advancement_adapter_policy WHERE connection_id=?",connection.id),policy:AdapterCapabilities=row?JSON.parse(String(row.capabilities)):defaults;
  transaction(db,()=>{db.prepare("DELETE FROM advancement_adapter_claims WHERE expires_at<=?").run(started);if(Number(row?.open_until??0)>started)throw new HttpError(503,"PROVIDER_CIRCUIT_OPEN","공급자 장애로 연결을 잠시 보류합니다.");const active=Number(one(db,"SELECT COUNT(*) AS n FROM advancement_adapter_claims WHERE connection_id=?",connection.id)?.n??0);if(active>=policy.maxConcurrent)throw new HttpError(429,"PROVIDER_CONCURRENCY","연결 동시 요청 한도입니다.");db.prepare("INSERT INTO advancement_adapter_claims VALUES(?,?,?)").run(claim,connection.id,started+policy.timeoutMs+1000);});
  try{let attempt=0;while(true){try{const remaining=policy.timeoutMs-(Date.now()-started);if(remaining<=0)throw new HttpError(504,"PROVIDER_DEADLINE","공급자 전체 제한 시간을 초과했습니다.");const result=await transport({...connection,requestTimeoutMs:remaining},method,payload,key);db.prepare("UPDATE advancement_adapter_policy SET failures=0,open_until=0 WHERE connection_id=?").run(connection.id);return result;}catch(error){const code=error instanceof HttpError?error.code:"PROVIDER_CONNECTION",retryable=["PROVIDER_RETRYABLE","PROVIDER_RATE_LIMIT"].includes(code),retryAfter=error instanceof HttpError&&"retryAfterMs" in error&&typeof error.retryAfterMs==="number"?error.retryAfterMs:0;
      if(!retryable||method==='POST'&&!policy.idempotentWrites||attempt>=policy.maxRetries){db.prepare("UPDATE advancement_adapter_policy SET failures=failures+1,open_until=CASE WHEN failures+1>=3 THEN ? ELSE open_until END WHERE connection_id=?").run(Date.now()+30000,connection.id);throw error;}
      const delay=Math.max(retryAfter,Math.min(2000,200*2**attempt)+Math.floor(Math.random()*100));if(Date.now()+delay>=started+policy.timeoutMs)throw error;attempt++;await new Promise<void>(resolve=>setTimeout(resolve,delay));}}
  }finally{db.prepare("DELETE FROM advancement_adapter_claims WHERE id=?").run(claim);}
}
