import { randomUUID } from "node:crypto";
import type { DatabaseSync } from "node:sqlite";
import type { ExpansionScope } from "../../src/domain/expansion";
import type { CatalogVersion } from "../../src/domain/advancement";
import { parseDeclarativePackage, verifyPackageIntegrity } from "../../src/domain/packages";
import { HttpError } from "../http";
import { many, now, one, text } from "../platform/common";
export class CatalogService {
  constructor(readonly db:DatabaseSync){}
  list(organizationId:string):CatalogVersion[]{return many(this.db,"SELECT * FROM advancement_catalog WHERE organization_id=? OR status='approved' ORDER BY created_at DESC LIMIT 200",organizationId).map(row=>({id:String(row.id),organizationId:String(row.organization_id),packageId:String(row.package_id),version:String(row.version),integrity:String(row.integrity),status:String(row.status) as CatalogVersion['status'],publisherId:String(row.publisher_id),reviewerId:row.reviewer_id?String(row.reviewer_id):null,license:String(row.license),supportContact:String(row.support_contact),evidence:String(row.evidence),createdAt:String(row.created_at)}));}
  async submit(scope:ExpansionScope,actor:string,input:Record<string,unknown>,assertCurrent:()=>void):Promise<CatalogVersion> {const manifest=parseDeclarativePackage(input.manifest);await verifyPackageIntegrity(manifest);assertCurrent();const id=randomUUID();this.db.prepare("INSERT INTO advancement_catalog VALUES(?,?,?,?,?,?,'pending',?,NULL,?,?,?,?)").run(id,scope.organizationId,manifest.id,manifest.version,manifest.integrity,JSON.stringify(manifest),actor,text(input.license,"라이선스",1000),text(input.supportContact,"지원 연락",300),text(input.evidence,"호환 검증 근거",2000),now());return this.list(scope.organizationId).find(item=>item.id===id)!;}
  review(scope:ExpansionScope,actor:string,id:string,input:Record<string,unknown>):CatalogVersion {const row=one(this.db,"SELECT * FROM advancement_catalog WHERE id=?",id);if(!row)throw new HttpError(404,"CATALOG_VERSION","팩 버전을 찾을 수 없습니다.");if(input.status!=='revoked'&&row.publisher_id===actor)throw new HttpError(403,"CATALOG_SELF_REVIEW","제출자가 자신의 팩을 승인할 수 없습니다.");if(!['approved','revoked'].includes(String(input.status)))throw new HttpError(400,"CATALOG_STATUS","검토 상태를 확인하세요.");this.db.prepare("UPDATE advancement_catalog SET status=?,reviewer_id=?,evidence=? WHERE id=?").run(String(input.status),actor,text(input.evidence,"검토 근거",2000),id);return this.list(scope.organizationId).find(item=>item.id===id)??{id,organizationId:String(row.organization_id),packageId:String(row.package_id),version:String(row.version),integrity:String(row.integrity),status:String(input.status) as CatalogVersion['status'],publisherId:String(row.publisher_id),reviewerId:actor,license:String(row.license),supportContact:String(row.support_contact),evidence:String(input.evidence),createdAt:String(row.created_at)};}
  assertInstall(packageId:string,version:string):void {const row=one(this.db,"SELECT status FROM advancement_catalog WHERE package_id=? AND version=?",packageId,version);if(row&&row.status!=='approved')throw new HttpError(409,"CATALOG_UNAVAILABLE","심사 대기 또는 회수된 팩 버전입니다.");}
  affected(packageId:string,version:string):string[]{return many(this.db,"SELECT id FROM projects WHERE EXISTS(SELECT 1 FROM json_each(projects.body,'$.blockPackages') p WHERE json_extract(p.value,'$.id')=? AND json_extract(p.value,'$.version')=?)",packageId,version).map(row=>String(row.id));}
}
