import { randomUUID } from "node:crypto";
import type { DatabaseSync } from "node:sqlite";
import type { ExpansionScope } from "../../src/domain/expansion";
import type { ConfigChange, ConfigSnapshot, FeatureFlag } from "../../src/domain/advancement";
import { safeConfig } from "../expansion/organizations";
import { HttpError } from "../http";
import { boolean, integer, many, now, one, text, transaction } from "../platform/common";
import { fingerprint, scopeKey } from "./common";
import { AuditJournal } from "./audit";
export function assertRuntimeFeature(db:DatabaseSync,key:string):void {const row=one(db,"SELECT value FROM runtime_state WHERE key='advancement:policy'");if(!row)return;const policy=JSON.parse(String(row.value)) as {lifecycle?:{state?:string};flags?:FeatureFlag[]};if(policy.lifecycle?.state&&policy.lifecycle.state!=='active')throw new HttpError(409,'ORGANIZATION_ARCHIVED','보관된 조직에서는 신규 운영 작업을 실행할 수 없습니다.');const flag=policy.flags?.find(item=>item.key===key);if(flag&&!flag.enabled&&(!flag.expiresAt||Date.parse(flag.expiresAt)>Date.now()))throw new HttpError(409,'FEATURE_PAUSED','이 환경의 신규 작업이 중지되어 있습니다.');}
export class ConfigService {
  constructor(readonly db:DatabaseSync,readonly audit:AuditJournal){}
  snapshot(scope:ExpansionScope):ConfigSnapshot {const row=one(this.db,"SELECT config_version,config FROM expansion_environments WHERE id=?",scope.environmentId??"");if(!row)throw new HttpError(404,"ENVIRONMENT","설정할 환경을 선택하세요.");return {scope,revision:Number(row.config_version),config:JSON.parse(String(row.config))};}
  preview(scope:ExpansionScope,actor:string,input:Record<string,unknown>):ConfigChange {const current=this.snapshot(scope),base=integer(input.baseRevision,"설정 revision",1),config=safeConfig(input.config);if(base!==current.revision)throw new HttpError(409,"CONFIG_CONFLICT","설정이 변경되었습니다. 다시 검토하세요.");const id=randomUUID(),expiry=Date.now()+900000,approvalFingerprint=fingerprint({scope,base,config,actor});this.db.prepare("INSERT INTO advancement_config_changes VALUES(?,?,?,?,?,?,?,?,NULL)").run(id,JSON.stringify(scope),scopeKey(scope),base,JSON.stringify(config),approvalFingerprint,actor,expiry);return {id,baseRevision:base,config,approvalFingerprint,expiresAt:new Date(expiry).toISOString(),appliedRevision:null};}
  apply(scope:ExpansionScope,actor:string,id:string,approval:unknown):ConfigSnapshot {return transaction(this.db,()=>{const row=one(this.db,"SELECT * FROM advancement_config_changes WHERE id=? AND scope_key=?",id,scopeKey(scope));if(!row||row.actor_id!==actor||row.fingerprint!==approval||Number(row.expires_at)<=Date.now())throw new HttpError(409,"CONFIG_REVIEW","이 환경의 유효한 설정 검토가 필요합니다.");if(row.applied_revision!==null)return this.snapshot(scope);const changed=this.db.prepare("UPDATE expansion_environments SET config=?,config_version=config_version+1,updated_at=? WHERE id=? AND config_version=?").run(String(row.config),now(),scope.environmentId!,Number(row.base_revision));if(!changed.changes)throw new HttpError(409,"CONFIG_CONFLICT","검토 이후 설정이 변경되었습니다.");this.db.prepare("UPDATE advancement_config_changes SET applied_revision=? WHERE id=?").run(Number(row.base_revision)+1,id);this.audit.append(scope.organizationId,actor,"config.apply",scope.environmentId!,"success",Number(row.base_revision),Number(row.base_revision)+1);return this.snapshot(scope);});}
  flags(scope:ExpansionScope):FeatureFlag[]{return many(this.db,"SELECT * FROM advancement_flags WHERE scope_key=? ORDER BY name",scopeKey(scope)).map(row=>({key:String(row.name),enabled:Boolean(row.enabled),revision:Number(row.revision),ownerId:String(row.owner_id),expiresAt:row.expires_at?new Date(Number(row.expires_at)).toISOString():null,reason:String(row.reason)}));}
  flag(scope:ExpansionScope,actor:string,key:string,input:Record<string,unknown>):FeatureFlag {if(!["publication","automation","paid-actions","external-writes","ai"].includes(key))throw new HttpError(400,"FLAG","지원하는 기능 플래그를 선택하세요.");const base=integer(input.baseRevision,"플래그 revision"),enabled=boolean(input.enabled,"활성화",true),expiry=input.expiresAt===undefined?null:Date.parse(text(input.expiresAt,"만료 시각",50));if(expiry!==null&&(!Number.isFinite(expiry)||expiry<=Date.now()))throw new HttpError(400,"FLAG_EXPIRY","미래 만료 시각이 필요합니다.");return transaction(this.db,()=>{const row=one(this.db,"SELECT revision FROM advancement_flags WHERE scope_key=? AND name=?",scopeKey(scope),key);if(Number(row?.revision??0)!==base)throw new HttpError(409,"FLAG_CONFLICT","플래그가 변경되었습니다.");this.db.prepare("INSERT INTO advancement_flags VALUES(?,?,?,?,?,?,?) ON CONFLICT(scope_key,name) DO UPDATE SET enabled=excluded.enabled,revision=excluded.revision,owner_id=excluded.owner_id,expires_at=excluded.expires_at,reason=excluded.reason").run(scopeKey(scope),key,enabled?1:0,base+1,actor,expiry,text(input.reason,"변경 사유",1000));this.audit.append(scope.organizationId,actor,"flag.change",key,"success",base,base+1);return this.flags(scope).find(flag=>flag.key===key)!;});}
  assertEnabled(scope:ExpansionScope,key:string):void {const row=one(this.db,"SELECT enabled,expires_at FROM advancement_flags WHERE scope_key=? AND name=?",scopeKey(scope),key);if(row&&!row.enabled&&(row.expires_at===null||Number(row.expires_at)>Date.now()))throw new HttpError(409,"FEATURE_PAUSED","이 환경에서 해당 신규 작업이 중지되어 있습니다.");}
  assertLifecycle(scope:ExpansionScope):void {const row=one(this.db,"SELECT state FROM advancement_lifecycle WHERE organization_id=?",scope.organizationId);if(row&&row.state!=="active")throw new HttpError(409,"ORGANIZATION_ARCHIVED","보관된 조직에서는 신규 운영 작업을 실행할 수 없습니다.");}
}
