import { randomUUID } from "node:crypto";
import type { DatabaseSync } from "node:sqlite";
import type { CreatorIdentity, ExpansionScope } from "../../src/domain/expansion";
import type { OrganizationLifecycle } from "../../src/domain/advancement";
import { HttpError } from "../http";
import { integer, now, one, text, transaction } from "../platform/common";
export class LifecycleService {
  constructor(readonly db:DatabaseSync){}
  state(organizationId:string):OrganizationLifecycle {const row=one(this.db,"SELECT * FROM advancement_lifecycle WHERE organization_id=?",organizationId);return {organizationId,revision:Number(row?.revision??0),state:String(row?.state??'active') as OrganizationLifecycle['state'],reason:String(row?.reason??''),updatedAt:String(row?.updated_at??now())};}
  change(scope:ExpansionScope,input:Record<string,unknown>):OrganizationLifecycle {const base=integer(input.baseRevision,"組織 revision"),state=input.state;if(!['active','archived','closing'].includes(String(state)))throw new HttpError(400,"LIFECYCLE_STATE","組織 운영 상태를 확인하세요.");transaction(this.db,()=>{if(this.state(scope.organizationId).revision!==base)throw new HttpError(409,"LIFECYCLE_CONFLICT","조직 운영 상태가 바뀌었습니다.");this.db.prepare("INSERT INTO advancement_lifecycle VALUES(?,?,?,?,?) ON CONFLICT(organization_id) DO UPDATE SET revision=excluded.revision,state=excluded.state,reason=excluded.reason,updated_at=excluded.updated_at").run(scope.organizationId,base+1,String(state),text(input.reason,"변경 사유",1000),now());if(state==='closing'){this.db.prepare("UPDATE expansion_credentials SET revoked=1 WHERE organization_id=?").run(scope.organizationId);this.db.prepare("UPDATE advancement_service_identities SET revoked=1 WHERE json_extract(scope,'$.organizationId')=?").run(scope.organizationId);this.db.prepare("UPDATE advancement_support_sessions SET revoked=1 WHERE json_extract(scope,'$.organizationId')=?").run(scope.organizationId);}});return this.state(scope.organizationId);}
  propose(scope:ExpansionScope,actor:CreatorIdentity,to:string):{id:string;expiresAt:string} {if(one(this.db,"SELECT role FROM expansion_memberships WHERE organization_id=? AND account_id=?",scope.organizationId,actor.id)?.role!=='owner'||!one(this.db,"SELECT account_id FROM expansion_memberships WHERE organization_id=? AND account_id=?",scope.organizationId,to))throw new HttpError(403,"HANDOFF_OWNER","현재 소유자가 같은 조직의 구성원에게 제안해야 합니다.");const id=randomUUID(),expiry=Date.now()+86400000;this.db.prepare("INSERT INTO advancement_handoffs VALUES(?,?,?,?,?,NULL)").run(id,scope.organizationId,actor.id,to,expiry);return {id,expiresAt:new Date(expiry).toISOString()};}
  accept(scope:ExpansionScope,actor:CreatorIdentity,id:string):void {transaction(this.db,()=>{const row=one(this.db,"SELECT * FROM advancement_handoffs WHERE id=? AND organization_id=? AND to_id=? AND accepted_at IS NULL AND expires_at>?",id,scope.organizationId,actor.id,Date.now());if(!row||one(this.db,"SELECT role FROM expansion_memberships WHERE organization_id=? AND account_id=?",scope.organizationId,String(row.from_id))?.role!=='owner'||!one(this.db,"SELECT id FROM creator_accounts WHERE id=? AND disabled=0",actor.id))throw new HttpError(409,"HANDOFF_EXPIRED","유효한 소유권 인계를 확인하세요.");this.db.prepare("UPDATE expansion_memberships SET role='owner' WHERE organization_id=? AND account_id=?").run(scope.organizationId,actor.id);this.db.prepare("UPDATE expansion_memberships SET role='admin' WHERE organization_id=? AND account_id=?").run(scope.organizationId,String(row.from_id));this.db.prepare("UPDATE advancement_handoffs SET accepted_at=? WHERE id=?").run(now(),id);});}
}
