import { randomUUID } from "node:crypto";
import type { DatabaseSync } from "node:sqlite";
import type { ExpansionScope } from "../../src/domain/expansion";
import type { SecretVersion } from "../../src/domain/advancement";
import { HttpError } from "../http";
import { getConnection, providerRequest, type Transport } from "../platform/connections";
import { many, now, one, text, transaction } from "../platform/common";
import { activeKeyId, decryptSecret, encryptSecret } from "./keyring";
import { fingerprint } from "./common";
export class EnvironmentSecrets {
  constructor(readonly db:DatabaseSync){}
  list(scope:ExpansionScope):SecretVersion[]{return many(this.db,"SELECT id,name,environment_id,version,key_id,status,tested_at,created_at FROM advancement_secret_versions WHERE environment_id=? AND organization_id=? ORDER BY name,version DESC LIMIT 500",scope.environmentId!,scope.organizationId).map(row=>({id:String(row.id),name:String(row.name),environmentId:String(row.environment_id),version:Number(row.version),keyId:String(row.key_id),status:String(row.status) as SecretVersion["status"],testedAt:row.tested_at?String(row.tested_at):null,createdAt:String(row.created_at)}));}
  register(scope:ExpansionScope,input:Record<string,unknown>):SecretVersion {const name=text(input.name,"비밀 참조",80);if(!scope.environmentId||!/^TENANT_[A-Z0-9_]{1,72}$/.test(name))throw new HttpError(400,"SECRET_SCOPE","환경과 TENANT_ 비밀 참조를 지정하세요.");const encrypted=encryptSecret(text(input.value,"비밀값",16000)),id=randomUUID();transaction(this.db,()=>{const version=Number(one(this.db,"SELECT MAX(version) AS n FROM advancement_secret_versions WHERE environment_id=? AND name=?",scope.environmentId!,name)?.n??0)+1;this.db.prepare("INSERT INTO advancement_secret_versions VALUES(?,?,?,?,?,?,?,?,?,'registered',NULL,?)").run(id,scope.organizationId,scope.workspaceId,scope.projectId,scope.environmentId!,name,version,encrypted,activeKeyId(),now());});return this.list(scope).find(row=>row.id===id)!;}
  private row(scope:ExpansionScope,id:string){const row=one(this.db,"SELECT * FROM advancement_secret_versions WHERE id=? AND environment_id=? AND organization_id=?",id,scope.environmentId!,scope.organizationId);if(!row)throw new HttpError(404,"SECRET_VERSION","이 환경의 비밀 버전을 찾을 수 없습니다.");return row;}
  async test(scope:ExpansionScope,id:string,site:DatabaseSync,connectionId:string,assertCurrent:()=>void,transport:Transport=providerRequest):Promise<{tested:true;version:SecretVersion}> {const row=this.row(scope,id);if(row.status==="retired")throw new HttpError(409,"SECRET_RETIRED","폐기된 버전입니다. 새 버전을 등록하세요.");const connection=getConnection(site,connectionId);if(connection.projectId!==scope.projectId||![connection.secretRef,connection.webhookSecretRef].includes(String(row.name)))throw new HttpError(403,"SECRET_CONNECTION","참조를 사용하는 해당 환경 연결을 선택하세요.");const value=decryptSecret(String(row.ciphertext));await transport({...connection,secretRef:String(row.name),resolveSecret:reference=>reference===row.name?value:connection.resolveSecret?.(reference)},"GET");assertCurrent();this.row(scope,id);this.db.prepare("UPDATE advancement_secret_versions SET status=CASE WHEN status='active' THEN status ELSE 'tested' END,tested_at=? WHERE id=? AND status<>'retired'").run(now(),id);this.db.prepare("INSERT INTO runtime_state VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run("secret:test:"+id,JSON.stringify({connectionId,fingerprint:fingerprint(connection),at:Date.now()}));return {tested:true,version:this.list(scope).find(row=>row.id===id)!};}
  activate(scope:ExpansionScope,id:string,site:DatabaseSync):SecretVersion {transaction(this.db,()=>{const row=this.row(scope,id),proof=one(this.db,"SELECT value FROM runtime_state WHERE key=?","secret:test:"+id);if(!proof||!["tested","active"].includes(String(row.status)))throw new HttpError(409,"SECRET_UNTESTED","해당 버전의 연결 시험이 필요합니다.");const test=JSON.parse(String(proof.value)) as {connectionId:string;fingerprint:string;at:number};if(Date.now()-test.at>900000||fingerprint(getConnection(site,test.connectionId))!==test.fingerprint)throw new HttpError(409,"SECRET_TEST_STALE","연결 설정이 바뀌었거나 시험이 만료되었습니다.");this.db.prepare("UPDATE advancement_secret_versions SET status='retired' WHERE environment_id=? AND name=? AND status='active' AND id<>?").run(scope.environmentId!,String(row.name),id);this.db.prepare("UPDATE advancement_secret_versions SET status='active' WHERE id=?").run(id);});return this.list(scope).find(row=>row.id===id)!;}
  retire(scope:ExpansionScope,id:string):void {const row=this.row(scope,id);if(row.status==="active")throw new HttpError(409,"SECRET_ACTIVE","다른 시험된 버전을 활성화한 뒤 이전 버전을 폐기하세요.");this.db.prepare("UPDATE advancement_secret_versions SET status='retired' WHERE id=?").run(id);}
}
