import { createHmac, randomBytes, randomUUID, timingSafeEqual } from "node:crypto";
import type { DatabaseSync } from "node:sqlite";
import type { CreatorIdentity, ExpansionScope } from "../../src/domain/expansion";
import type { SecurityStatus, StepUpInput } from "../../src/domain/advancement";
import { HttpError } from "../http";
import { hash, now, one, text } from "../platform/common";
import { verifyPasswordHash } from "../platform/auth";
import { decryptSecret, encryptSecret } from "./keyring";
import { fingerprint, scopeKey } from "./common";
const alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
function base32(bytes:Buffer):string {let bits=0,value=0,result="";for(const byte of bytes){value=(value<<8)|byte;bits+=8;while(bits>=5){result+=alphabet[(value>>>(bits-5))&31];bits-=5;}}if(bits)result+=alphabet[(value<<(5-bits))&31];return result;}
function decode(value:string):Buffer {let bits=0,buffer=0;const bytes:number[]=[];for(const character of value){const index=alphabet.indexOf(character);if(index<0)throw new HttpError(400,"TOTP_SECRET","인증 키를 확인하세요.");buffer=(buffer<<5)|index;bits+=5;if(bits>=8){bytes.push((buffer>>>(bits-8))&255);bits-=8;}}return Buffer.from(bytes);}
export function totp(secret:string,clock=Date.now(),digits=6,algorithm="sha1"):string {const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(clock/30000)));const mac=createHmac(algorithm,decode(secret)).update(counter).digest(),offset=mac[mac.length-1]!&15,value=(mac.readUInt32BE(offset)&0x7fffffff)%10**digits;return String(value).padStart(digits,"0");}
const equal=(left:string,right:string):boolean=>left.length===right.length&&timingSafeEqual(Buffer.from(left),Buffer.from(right));
export class SecurityService {
  constructor(readonly db:DatabaseSync,readonly clock:()=>number=Date.now){}
  status(actor:CreatorIdentity|null,localOwner=false):SecurityStatus {const row=actor?one(this.db,"SELECT * FROM advancement_mfa WHERE account_id=?",actor.id):null;return {enabled:Boolean(row?.secret),enrolledAt:row?.enrolled_at?String(row.enrolled_at):null,recoveryCodesRemaining:row?JSON.parse(String(row.recovery_hashes)).length:0,stepUpRequired:!localOwner};}
  private async password(actor:CreatorIdentity,value:unknown):Promise<void> {const row=one(this.db,"SELECT password_hash,disabled FROM creator_accounts WHERE id=?",actor.id),valid=await verifyPasswordHash(text(value,"비밀번호",128),row?String(row.password_hash):null);if(!valid||!row||row.disabled)throw new HttpError(401,"REAUTHENTICATE","다시 인증하세요.");}
  private proof(actor:CreatorIdentity,input:{code?:unknown;recoveryCode?:unknown}):void {
    const row=one(this.db,"SELECT * FROM advancement_mfa WHERE account_id=?",actor.id);if(!row?.secret)throw new HttpError(403,"MFA_REQUIRED","인증 앱을 먼저 등록하세요.");const clock=this.clock();if(Number(row.reset_at)>clock&&Number(row.failures)>=10)throw new HttpError(429,"MFA_LIMIT","잠시 후 인증을 다시 시도하세요.");
    let counter:number|null=null,recovery:string|null=null;const codes=JSON.parse(String(row.recovery_hashes)) as string[];
    if(typeof input.recoveryCode==="string"&&codes.includes(hash(input.recoveryCode)))recovery=hash(input.recoveryCode);
    if(typeof input.code==="string"&&/^\d{6}$/.test(input.code)){const secret=decryptSecret(String(row.secret));for(const delta of [-1,0,1]){const candidate=Math.floor(clock/30000)+delta;if(candidate>Number(row.last_counter)&&equal(totp(secret,candidate*30000),input.code)){counter=candidate;break;}}}
    if(counter===null&&!recovery){this.db.prepare("UPDATE advancement_mfa SET failures=CASE WHEN reset_at<=? THEN 1 ELSE failures+1 END,reset_at=CASE WHEN reset_at<=? THEN ? ELSE reset_at END WHERE account_id=?").run(clock,clock,clock+300000,actor.id);throw new HttpError(401,"MFA_CODE","인증 코드가 만료되었거나 사용되었습니다.");}
    const changed=this.db.prepare("UPDATE advancement_mfa SET last_counter=?,recovery_hashes=?,failures=0,reset_at=0 WHERE account_id=? AND last_counter=? AND recovery_hashes=?").run(counter??Number(row.last_counter),JSON.stringify(recovery?codes.filter(code=>code!==recovery):codes),actor.id,Number(row.last_counter),String(row.recovery_hashes));if(!changed.changes)throw new HttpError(409,"MFA_REPLAY","인증 코드가 이미 사용되었습니다.");
  }
  async enroll(actor:CreatorIdentity,input:{password?:unknown;code?:unknown;recoveryCode?:unknown}):Promise<{secret:string;otpauthUrl:string;expiresAt:string}> {await this.password(actor,input.password);if(this.status(actor).enabled)this.proof(actor,input);const secret=base32(randomBytes(20)),expiry=this.clock()+600000;this.db.prepare("INSERT INTO advancement_mfa(account_id,pending_secret,pending_until) VALUES(?,?,?) ON CONFLICT(account_id) DO UPDATE SET pending_secret=excluded.pending_secret,pending_until=excluded.pending_until").run(actor.id,encryptSecret(secret),expiry);return {secret,otpauthUrl:`otpauth://totp/Automade:${encodeURIComponent(actor.id)}?secret=${secret}&issuer=Automade&algorithm=SHA1&digits=6&period=30`,expiresAt:new Date(expiry).toISOString()};}
  confirm(actor:CreatorIdentity,code:unknown):{recoveryCodes:string[]} {const row=one(this.db,"SELECT * FROM advancement_mfa WHERE account_id=?",actor.id);if(!row?.pending_secret||Number(row.pending_until)<=this.clock()||typeof code!=="string"||!equal(totp(decryptSecret(String(row.pending_secret)),this.clock()),code))throw new HttpError(401,"MFA_ENROLLMENT","등록 코드와 유효 시간을 확인하세요.");const codes=Array.from({length:10},()=>randomBytes(16).toString("hex"));this.db.prepare("UPDATE advancement_mfa SET secret=pending_secret,pending_secret=NULL,pending_until=0,last_counter=?,recovery_hashes=?,enrolled_at=? WHERE account_id=? AND pending_secret=?").run(Math.floor(this.clock()/30000),JSON.stringify(codes.map(hash)),now(),actor.id,String(row.pending_secret));return {recoveryCodes:codes};}
  async issue(actor:CreatorIdentity,input:StepUpInput,scope?:ExpansionScope):Promise<{token:string;expiresAt:string}> {await this.password(actor,input.password);this.proof(actor,input);if(!/^(POST|PUT|PATCH|DELETE)$/.test(input.method)||!/^\/api\/[A-Za-z0-9/_:.-]{1,300}$/.test(input.path))throw new HttpError(400,"STEP_UP_TARGET","확인할 작업 경로를 지정하세요.");const token=randomBytes(32).toString("hex"),expiry=this.clock()+300000;this.db.prepare("INSERT INTO advancement_step_up VALUES(?,?,?,?,?,?,?,?,NULL)").run(hash(token),actor.id,actor.sessionId,input.method,input.path,scopeKey(scope),fingerprint(input.payload),expiry);return {token,expiresAt:new Date(expiry).toISOString()};}
  consume(actor:CreatorIdentity,token:unknown,method:string,path:string,scope:ExpansionScope|undefined,payload:unknown):void {if(typeof token!=="string")throw new HttpError(403,"STEP_UP_REQUIRED","이 작업의 추가 인증이 필요합니다.");const changed=this.db.prepare("UPDATE advancement_step_up SET used_at=? WHERE token_hash=? AND account_id=? AND session_id=? AND method=? AND path=? AND scope_key=? AND fingerprint=? AND expires_at>? AND used_at IS NULL").run(now(),hash(token),actor.id,actor.sessionId,method,path,scopeKey(scope),fingerprint(payload),this.clock());if(!changed.changes)throw new HttpError(403,"STEP_UP_REQUIRED","추가 인증이 만료되었거나 대상 작업이 달라졌습니다.");}
  recovery(actor:CreatorIdentity):{enabled:boolean} {this.db.prepare("DELETE FROM advancement_step_up WHERE account_id=?").run(actor.id);return {enabled:this.status(actor).enabled};}
  newOperationId():string{return randomUUID();}
}
