import type { IncomingMessage, ServerResponse } from "node:http";
import type { Store } from "../store";
import type { ExpansionService } from "../expansion/service";
import type { AdvancementContext, StepUpInput } from "../../src/domain/advancement";
import type { CreatorIdentity, ExpansionCapability, ExpansionScope } from "../../src/domain/expansion";
import type { Project } from "../../src/domain/types";
import { record, parseProject } from "../../src/domain/validation";
import { body, HttpError, reply } from "../http";
import { actorId } from "../expansion/access";
import { integer, one, text } from "../platform/common";
import { AuditJournal } from "./audit";
import { ConfigService } from "./config";
import { SecurityService } from "./security";
import { IdentityService } from "./identities";
import { EnvironmentSecrets } from "./secrets";
import { rotateKeyBatch, activeKeyId } from "./keyring";
import { simulateWorkflow } from "./workflows";
import { ledger } from "./ledger";
import { IndexedContentService } from "./content";
import type { ContentContext } from "../../src/domain/contentContracts";
import { EvidenceService } from "./reconciliation";
import { LifecycleService } from "./lifecycle";
import { CatalogService } from "./catalog";
import { AdapterPolicyService } from "./adapters";
import { PrivacyService } from "./privacy";
import { BackupService } from "./backups";
import { randomUUID } from "node:crypto";
import { mkdir, copyFile, stat } from "node:fs/promises";
import path from "node:path";
import { fingerprint } from "./common";
import { hash, many, now } from "../platform/common";
import { parseCapabilities } from "../expansion/access";
import { bindOperation } from "../operationContext";
export interface AdvancementOptions {
  dataRoot:string;
  exportRoot?:string;
  siteData:(scope:ExpansionScope)=>Promise<Store>;
  rawProject?:(id:string)=>Project|null;
  enqueueJob?:(kind:string,scope:ExpansionScope,payload:unknown,key:string,actorId?:string)=>Promise<{id:string;status:string}>;
  backupScope?:(scope:ExpansionScope)=>Promise<{id:string}>;
  restoreScope?:(scope:ExpansionScope,backupId:string)=>Promise<unknown>;
  withFreeze?:<T>(scope:ExpansionScope,work:(site:Store)=>Promise<T>)=>Promise<T>;
  emit?:(scope:ExpansionScope,event:unknown)=>void;
  verifyExternal?:(scope:ExpansionScope,kind:"payment"|"deployment"|"work"|"restore",targetId:string)=>Promise<{source:string;resolution:"completed"|"no-effect";evidence:unknown}>;
}
export class AdvancementService {
  readonly audit:AuditJournal;readonly config:ConfigService;readonly security:SecurityService;readonly identities:IdentityService;readonly secrets:EnvironmentSecrets;
  readonly content:IndexedContentService;readonly evidence:EvidenceService;readonly lifecycle:LifecycleService;readonly catalog:CatalogService;
  readonly privacy:PrivacyService;readonly backups:BackupService;
  constructor(readonly store:Store,readonly expansion:ExpansionService,readonly options:AdvancementOptions){this.audit=new AuditJournal(store.db);this.config=new ConfigService(store.db,this.audit);this.security=new SecurityService(store.db);this.identities=new IdentityService(store.db,expansion.access);this.secrets=new EnvironmentSecrets(store.db);this.content=new IndexedContentService(store.db,options.rawProject??(id=>store.rawProject(id)));this.evidence=new EvidenceService(store.db);this.lifecycle=new LifecycleService(store.db);this.catalog=new CatalogService(store.db);this.privacy=new PrivacyService(store.db);this.backups=new BackupService(store,expansion,options.dataRoot,options.exportRoot);}
  platformAdministrator(creator:CreatorIdentity|null,localOwner:boolean):void {if(localOwner&&this.expansion.mode==='local')return;const email=creator?one(this.store.db,"SELECT email FROM creator_accounts WHERE id=? AND disabled=0",creator.id)?.email:null;if(!email||!process.env.STUDIO_ADMIN_EMAIL||email!==process.env.STUDIO_ADMIN_EMAIL)throw new HttpError(403,"PLATFORM_ADMIN_REQUIRED","중앙 운영 관리자의 승인이 필요합니다.");}
  assertJob(scope:ExpansionScope,kind:string):void {this.config.assertLifecycle(scope);this.config.assertEnabled(scope,kind.startsWith("workflow")?"automation":kind.startsWith("site.")||kind.startsWith("content.publish")?"publication":"paid-actions");}
  assertRequest(req:IncomingMessage,url:URL,context:{creator:CreatorIdentity|null;localOwner:boolean;scope?:ExpansionScope|null;input?:unknown}):void {
    bindOperation(context.scope??undefined,context.creator?.id??(context.localOwner?'local-owner':undefined),context.creator?.sessionId.startsWith('service:')?'service':context.creator?'creator':context.localOwner?'local-owner':undefined);
    const mutation=!['GET','HEAD','OPTIONS'].includes(req.method??"GET"),scope=context.scope??undefined;if(!mutation)return;
    const repair=/\/(?:reconcile|reconciliation|verify|restore|backup|backup-sets|rehearsal|lifecycle|handoffs|step-up|enrollment|retire|revoke|logout|cancel|stop)(?:\/|$)/.test(url.pathname);
    if(!scope&&!repair){const input=context.input&&typeof context.input==='object'?record(context.input):{},organizationId=typeof input.organizationId==='string'?input.organizationId:url.searchParams.get('organizationId')??url.pathname.match(/\/organizations\/([^/]+)/)?.[1];if(organizationId)this.config.assertLifecycle({organizationId,workspaceId:'',projectId:''});}
    if(scope&&!repair){this.config.assertLifecycle(scope);if(/exports|generate|promotion|publish/.test(url.pathname))this.config.assertEnabled(scope,"publication");if(/workflow|automation/.test(url.pathname))this.config.assertEnabled(scope,"automation");if(/connections|adapters|outbox/.test(url.pathname))this.config.assertEnabled(scope,"external-writes");if(/generate|proposal/.test(url.pathname))this.config.assertEnabled(scope,"ai");if(/checkout|subscription|refund/.test(url.pathname))this.config.assertEnabled(scope,"paid-actions");}
    if(this.expansion.mode!=="managed")return;
    const sensitive=/\/(?:secrets|keyring|service-identities|support-sessions|lifecycle|handoffs|transfer|members|invites|environments|workspaces|sites|organizations|credentials|connections|refund|flags|config\/changes\/[^/]+\/apply|data-restore|restore|billing|deployment|promotion|storage-migrations|worker-policy|alerts)(?:\/|$)/.test(url.pathname)||/backup-sets\/.+\/restore$/.test(url.pathname);
    if(!sensitive)return;if(!context.creator)throw new HttpError(401,"CREATOR_REQUIRED","제작자 계정으로 추가 인증하세요.");this.security.consume(context.creator,req.headers['x-step-up-token'],req.method??"POST",url.pathname,scope,context.input);this.audit.append(scope?.organizationId??"local",context.creator.id,"security.step-up.consume",url.pathname,"authorized");
  }
  private scope(url:URL,input:Record<string,unknown>,context:AdvancementContext,capability:ExpansionCapability):ExpansionScope {for(const name of ["projectId","environmentId"]){if(input[name]!==undefined&&url.searchParams.get(name)&&input[name]!==url.searchParams.get(name))throw new HttpError(403,"SCOPE_MISMATCH","본문과 요청 대상 범위가 다릅니다.");}const scope=this.expansion.access.resolve({projectId:typeof input.projectId==="string"?input.projectId:url.searchParams.get("projectId")??undefined,environmentId:typeof input.environmentId==="string"?input.environmentId:url.searchParams.get("environmentId")??undefined});return this.expansion.access.authorize(context.creator,scope,capability,context.localOwner&&this.expansion.mode==="local");}
  async handle(req:IncomingMessage,res:ServerResponse,url:URL,context:AdvancementContext):Promise<boolean> {
    if(!url.pathname.startsWith("/api/advancement/")||url.pathname.startsWith("/api/advancement/runtime/"))return false;
    const local=context.localOwner&&this.expansion.mode==="local",creator=context.creator;if(!creator&&!local)throw new HttpError(401,"CREATOR_REQUIRED","제작자 로그인이 필요합니다.");
    const method=req.method??"GET",route=url.pathname.slice("/api/advancement/".length),input=method==='GET'||method==='DELETE'?{}:record(await body(req,8_000_000));if(method!=='GET'&&!local)this.expansion.auth.csrf(req);
    const send=(value:unknown,status=200):true=>{reply(res,status,value);return true;},owned=(capability:ExpansionCapability)=>this.scope(url,input,context,capability),actor=actorId(creator,local);
    if(route==='security'&&method==='GET')return send(this.security.status(creator,local));
    if(route.startsWith('security/')&&method==='POST'){if(!creator)throw new HttpError(401,"CREATOR_REQUIRED","인증 앱 등록에는 제작자 계정이 필요합니다.");this.expansion.auth.rate(req,route);if(route==='security/enrollment')return send(await this.security.enroll(creator,input));if(route==='security/enrollment/confirm')return send(this.security.confirm(creator,input.code));if(route==='security/step-up'){let scope:ExpansionScope|undefined;if(input.projectId||input.environmentId)scope=owned('project.read');const value:StepUpInput={password:text(input.password,"비밀번호",128),method:text(input.method,"대상 method",10),path:text(input.path,"대상 경로",320),payload:input.payload,...(typeof input.code==='string'?{code:input.code}:{}),...(typeof input.recoveryCode==='string'?{recoveryCode:input.recoveryCode}:{})};return send(await this.security.issue(creator,value,scope));}}
    const required:ExpansionCapability=route.startsWith('secrets')||route.startsWith('keyring')?'secret.rotate':route.startsWith('audit')||route.startsWith('service-identities')||route.startsWith('support-sessions')?'team.manage':route.startsWith('lifecycle')||route==='handoffs'?'org.manage':route.startsWith('config')||route.startsWith('flags')?method==='GET'?'project.read':'project.publish':route.startsWith('adapter')?'connection.manage':route.startsWith('workflows')?'automation.manage':route.startsWith('usage')?'billing.manage':route.startsWith('backup-sets')?'backup.restore':route.startsWith('privacy')||route.startsWith('reconciliation')||route==='ledger'?method==='GET'?'data.read':'data.write':route.startsWith('catalog')?method==='GET'?'project.read':'asset.manage':input.state==='approved'?'review.approve':['published','scheduled','unpublish','restore'].includes(String(input.state))?'project.publish':route.startsWith('content')||route.startsWith('models')?'project.edit':'project.read';
    let scope:ExpansionScope|undefined;if(url.searchParams.has('projectId')||input.projectId||url.searchParams.has('environmentId')||input.environmentId)scope=owned(required);this.assertRequest(req,url,{creator,localOwner:local,scope,input});
    if(route==='config'&&method==='GET')return send(this.config.snapshot(owned('project.read')));
    if(route==='config/changes'&&method==='POST')return send(this.config.preview(owned('project.publish'),actor,input),201);
    const change=route.match(/^config\/changes\/([^/]+)\/apply$/);if(change&&method==='POST')return send(this.config.apply(owned('project.publish'),actor,change[1]!,input.approvalFingerprint));
    if(route==='flags'&&method==='GET')return send(this.config.flags(owned('project.read')));const flag=route.match(/^flags\/([^/]+)$/);if(flag&&method==='PUT'){const target=owned('project.publish'),value=this.config.flag(target,actor,flag[1]!,input);await this.syncRuntimePolicy(target);return send(value);}
    if(route==='audit'&&method==='GET'){const target=owned('team.manage');return send(this.audit.list(target.organizationId,url.searchParams.has('before')?integer(Number(url.searchParams.get('before')),"감사 cursor",1,Number.MAX_SAFE_INTEGER):undefined,integer(Number(url.searchParams.get('limit')??50),"조회 수",1,100)));}
    if(route==='audit/checkpoint'&&method==='GET'){owned('team.manage');return send(this.audit.checkpoint());}
    if(route==='service-identities'&&method==='GET')return send(this.identities.list(owned('team.manage')));if(route==='service-identities'&&method==='POST')return send(this.identities.create(owned('team.manage'),creator,local,input),201);
    const identity=route.match(/^service-identities\/([^/]+)(?:\/(keys))?$/);if(identity&&method==='POST'&&identity[2])return send(this.identities.rotate(owned('team.manage'),identity[1]!,integer(input.graceMinutes??15,"전환 분",0,30)));if(identity&&method==='DELETE'){this.identities.revoke(owned('team.manage'),identity[1]!);return send({revoked:true});}
    if(route==='secrets/versions'&&method==='GET')return send(this.secrets.list(owned('secret.rotate')));if(route==='secrets/versions'&&method==='POST')return send(this.secrets.register(owned('secret.rotate'),input),201);
    const secret=route.match(/^secrets\/versions\/([^/]+)\/(test|activate|retire)$/);if(secret&&method==='POST'){const target=owned('secret.rotate'),site=await this.options.siteData(target);const verify=()=>this.expansion.access.authorize(creator,target,'secret.rotate',local);if(secret[2]==='test')return send(await this.secrets.test(target,secret[1]!,site.db,text(input.connectionId,"연결",100),verify));if(secret[2]==='activate')return send(this.secrets.activate(target,secret[1]!,site.db));this.secrets.retire(target,secret[1]!);return send({retired:true});}
    if(route==='keyring'&&method==='GET'){owned('secret.rotate');this.platformAdministrator(creator,local);return send({activeKeyId:activeKeyId(),rotations:many(this.store.db,'SELECT id,target_key_id AS targetKeyId,status,processed,created_at AS createdAt,updated_at AS updatedAt FROM advancement_key_rotation ORDER BY updated_at DESC LIMIT 100')});}if(route==='keyring/rotations'&&method==='POST'){owned('secret.rotate');this.platformAdministrator(creator,local);return send(rotateKeyBatch(this.store.db,text(input.id,"회전 작업 ID",100),integer(input.limit??100,"배치 수",1,500)));}
    const workflow=route.match(/^workflows\/([^/]+)\/(simulation|execute-reviewed)$/);if(workflow&&method==='POST'){const target=owned('automation.manage'),value=this.expansion.workflows.list(target).find(item=>item.id===workflow[1]);if(!value)throw new HttpError(404,"WORKFLOW","이 범위의 자동화를 찾을 수 없습니다.");const review=fingerprint([target,actor,value.id,value.revision,input.payload]);if(workflow[2]==='simulation'){const result=simulateWorkflow(value,input.payload,(await this.options.siteData(target)).db);this.store.operations.setState('advancement:workflow-review:'+review,{expiresAt:Date.now()+900000});return send(result);}const approval=this.store.operations.state('advancement:workflow-review:'+review) as {expiresAt?:number}|null;if(value.trigger!=='manual'||value.revision!==input.expectedRevision||!approval||Number(approval.expiresAt)<=Date.now())throw new HttpError(409,"WORKFLOW_REVIEW_STALE","같은 내용과 버전의 수동 자동화를 먼저 시험하세요.");const ids=this.expansion.workflows.events(target,'manual',input.payload,'reviewed-'+hash(text(input.key,"실행 키",100)),actor,{workflowId:value.id,expectedRevision:value.revision}),jobs=[];for(const id of ids)jobs.push(await this.expansion.options.enqueueJob('workflow.run',target,{runId:id},'workflow-'+id,actor));return send({jobs,matched:ids.length>0,workflowId:value.id,revision:value.revision},202);}
    if(route==='ledger'&&method==='GET'){const target=owned('data.read'),realm=url.searchParams.get('realm')??'orders';if(!['orders','subscriptions'].includes(realm))throw new HttpError(400,"LEDGER_REALM","원장 종류를 확인하세요.");return send(ledger((await this.options.siteData(target)).db,target.projectId,realm,integer(Number(url.searchParams.get('limit')??50),"조회 수",1,100),url.searchParams.get('before')??undefined));}
    if(route==='usage'&&method==='GET'){const target=owned('billing.manage');return send({budgets:this.expansion.usage.budget(target.organizationId),reservations:this.expansion.usage.list(target),...this.expansion.usage.evidence(target),providerBilling:'not-configured'});}
    if(route==='adapter-policies'&&method==='GET'){const target=owned('connection.manage');return send(new AdapterPolicyService((await this.options.siteData(target)).db).list(target.projectId));}const adapter=route.match(/^adapter-policies\/([^/]+)$/);if(adapter&&method==='PUT'){const target=owned('connection.manage');return send(new AdapterPolicyService((await this.options.siteData(target)).db).save(target.projectId,adapter[1]!,input));}
    if(route==='reconciliation-cases'&&method==='GET')return send(this.evidence.list(owned('data.read')));if(route==='reconciliation-cases'&&method==='POST')return send(this.evidence.create(owned('data.write'),input),201);
    const evidence=route.match(/^reconciliation-cases\/([^/]+)\/verify$/);if(evidence&&method==='POST'){const target=owned('data.write'),site=await this.options.siteData(target),verify=()=>this.expansion.access.authorize(creator,target,'data.write',local);return send(await this.evidence.verify(target,evidence[1]!,integer(input.baseRevision,"대사 revision",1),site.db,verify,this.options.verifyExternal?(kind,id)=>this.options.verifyExternal!(target,kind,id):undefined));}
    if(route==='lifecycle'&&method==='GET')return send(this.lifecycle.state(owned('org.manage').organizationId));if(route==='lifecycle'&&method==='PUT'){const target=owned('org.manage'),value=this.lifecycle.change(target,input);await this.syncRuntimePolicy(target,true);return send(value);}
    if(route==='handoffs'&&method==='POST'){const target=owned('org.manage');if(!creator)throw new HttpError(401,"CREATOR_REQUIRED","인계에는 제작자 계정이 필요합니다.");return send(this.lifecycle.propose(target,creator,text(input.accountId,"받는 계정",100)),201);}const handoff=route.match(/^handoffs\/([^/]+)\/accept$/);if(handoff&&method==='POST'){const target=owned('project.read');if(!creator)throw new HttpError(401,"CREATOR_REQUIRED","받는 제작자로 로그인하세요.");this.lifecycle.accept(target,creator,handoff[1]!);return send({accepted:true});}
    if(route==='catalog'&&method==='GET')return send(this.catalog.list(owned('project.read').organizationId));if(route==='catalog'&&method==='POST'){const target=owned('asset.manage');return send(await this.catalog.submit(target,actor,input,()=>this.expansion.access.authorize(creator,target,'asset.manage',local)),201);}const catalog=route.match(/^catalog\/([^/]+)\/review$/);if(catalog&&method==='POST'){this.platformAdministrator(creator,local);return send(this.catalog.review(owned('asset.manage'),actor,catalog[1]!,input));}
    const cmsRoute=route.replace(/^(content\/[^/]+)\/records(?=\/|$)/,'$1').replace(/\/translations\/([^/]+)$/,(_,language:string)=>{input.language=language;return '/translations';});const cms=cmsRoute.match(/^content\/([^/]+)(?:\/([^/]+))?(?:\/(transitions|translations))?$/);if(cms){const target=owned(method==='GET'?'project.edit':input.state==='approved'?'review.approve':['published','scheduled'].includes(String(input.state))?'project.publish':'project.edit'),ctx:ContentContext={scope:target,actorId:actor,assertApprover:approver=>{this.expansion.authorizeJob(target,approver,'review.approve');},authorize:cap=>{this.expansion.access.authorize(creator,target,cap,local);},emit:this.options.emit?event=>this.options.emit!(target,event):undefined};if(method==='GET')return send(cms[2]?this.content.get(target.projectId,cms[1]!,cms[2]!,{member:true,manage:true,view:'draft'}):this.content.query(target.projectId,cms[1]!,url.searchParams,{member:true,manage:true,view:'draft'}));if(!cms[2])throw new HttpError(400,"CONTENT_RECORD","레코드 ID를 지정하세요.");const expectedRevision=integer(input.expectedRevision,"레코드 revision",0),commandId=text(input.commandId,"명령 ID",100);if(method==='PUT'&&!cms[3])return send(this.content.upsert(ctx,cms[1]!,cms[2]!,{record:this.parseContentInput(target.projectId,cms[1]!,cms[2]!,input.record),expectedRevision,commandId}));if(method==='POST'&&cms[3]==='transitions')return send(this.content.transition(ctx,cms[1]!,cms[2]!,{state:input.state as Parameters<IndexedContentService['transition']>[3]['state'],expectedRevision,commandId,...(typeof input.publishAt==='string'?{publishAt:input.publishAt}:{} )}));if(method==='POST'&&cms[3]==='translations')return send(this.content.translation(ctx,cms[1]!,cms[2]!,text(input.language,"언어",50),{state:input.state as Parameters<IndexedContentService['translation']>[4]['state'],expectedRevision,commandId,...(typeof input.assignee==='string'?{assignee:input.assignee}:{}),...(input.glossaryVersion===undefined?{}:{glossaryVersion:integer(input.glossaryVersion,'용어집 버전',0)})}));}
    const model=route.match(/^models\/([^/]+)\/(preview|run)$/);if(model&&method==='POST'){const target=owned('project.edit'),ctx:ContentContext={scope:target,actorId:actor,assertApprover:approver=>{this.expansion.authorizeJob(target,approver,'review.approve');},authorize:cap=>{this.expansion.access.authorize(creator,target,cap,local);},emit:this.options.emit?event=>this.options.emit!(target,event):undefined};return send(model[2]==='preview'?this.content.schemaPreview(ctx,model[1]!,{schema:input.schema}):this.content.schemaRun(ctx,model[1]!,{limit:integer(input.limit??100,"배치 크기",1,500)}));}
    if(route==='impact'&&method==='GET'){const target=owned('project.read');return send(this.content.impact({scope:target,actorId:actor,assertApprover:approver=>{this.expansion.authorizeJob(target,approver,'review.approve');},authorize:cap=>{this.expansion.access.authorize(creator,target,cap,local);}},text(url.searchParams.get('targetType'),"참조 유형",50),text(url.searchParams.get('targetId'),"참조 ID",200)));}
    if(route==='privacy-requests'&&method==='GET')return send(this.privacy.list(owned('data.read')));if(route==='privacy-requests'&&method==='POST'){const target=owned('data.write');return send(this.privacy.create(target,(await this.options.siteData(target)).db,input),201);}const privacy=route.match(/^privacy-requests\/([^/]+)\/run$/);if(privacy&&method==='POST'){const target=owned('data.write');if(input.confirm!==true)throw new HttpError(400,"PRIVACY_CONFIRM","처리 범위를 확인하세요.");return send(this.privacy.run(target,privacy[1]!, (await this.options.siteData(target)).db));}
    if(route==='backup-sets'&&method==='GET')return send(this.backups.list(owned('backup.restore')));if(route==='backup-sets'&&method==='POST'){this.platformAdministrator(creator,local);const target=owned('backup.restore');return send(await this.backups.create(target,await this.options.siteData(target),this.options.withFreeze),201);}const backup=route.match(/^backup-sets\/([^/]+)\/(rehearsal|restore)$/);if(backup&&method==='POST'){this.platformAdministrator(creator,local);const target=owned('backup.restore');if(input.confirm!==true)throw new HttpError(400,"BACKUP_CONFIRM","복원 범위와 보관할 키 버전을 확인하세요.");if(backup[2]==='rehearsal')return send(await this.backups.rehearse(target,backup[1]!));if(!this.options.restoreScope)throw new HttpError(503,"RESTORE_UNCONFIGURED","실행 환경의 복원 연결이 필요합니다.");const source=await this.backups.environmentFile(target,backup[1]!);await this.backups.restoreArtifacts(target,backup[1]!);const id=randomUUID(),folder=path.join(this.options.dataRoot,'backups',target.projectId);await mkdir(folder,{recursive:true});const file=path.join(folder,id+'.sqlite');await copyFile(source,file);this.expansion.access.authorize(creator,target,'backup.restore',local);this.store.operations.addBackup({id,projectId:target.projectId,releaseId:null,createdAt:now(),bytes:(await stat(file)).size,reason:'backup-set-restore-candidate',submissions:0,tables:0},file);this.store.operations.setState('backup:scope:'+id,{dataKey:target.dataKey??target.projectId,environmentId:target.environmentId??null});return send(await this.options.restoreScope(target,id));}
    if(route==='support-sessions'&&method==='GET'){const target=owned('team.manage');return send(many(this.store.db,"SELECT id,support_id AS supportId,approved_by AS approvedBy,capabilities,reason,expires_at AS expiresAt,revoked,created_at AS createdAt FROM advancement_support_sessions WHERE json_extract(scope,'$.organizationId')=? AND json_extract(scope,'$.projectId')=? AND COALESCE(json_extract(scope,'$.environmentId'),'')=? ORDER BY created_at DESC LIMIT 100",target.organizationId,target.projectId,target.environmentId??'').map(row=>({...row,capabilities:JSON.parse(String(row.capabilities)),revoked:Boolean(row.revoked),expiresAt:new Date(Number(row.expiresAt)).toISOString()})));}
    if(route==='support-sessions'&&method==='POST'){const target=owned('team.manage'),supportId=text(input.supportId,"지원 제작자 ID",100),capabilities=parseCapabilities(input.capabilities),available=this.expansion.access.capabilities(creator,target,local),expiry=Date.parse(text(input.expiresAt,"지원 만료 시각",50));if(!one(this.store.db,"SELECT 1 FROM expansion_memberships WHERE account_id=? AND organization_id=?",supportId,target.organizationId)||capabilities.some(cap=>!available.includes(cap)||['org.manage','team.manage','billing.manage','secret.rotate','backup.restore','workspace.manage'].includes(cap))||!capabilities.length||!Number.isFinite(expiry)||expiry<=Date.now()||expiry>Date.now()+86400000)throw new HttpError(400,"SUPPORT_SCOPE","지원 대상·업무 범위·24시간 이내 만료를 확인하세요.");const id=randomUUID();this.store.db.prepare("INSERT INTO advancement_support_sessions VALUES(?,?,?,?,?,?,?,0,?)").run(id,JSON.stringify(target),supportId,actor,JSON.stringify(capabilities),text(input.reason,"지원 사유",1000),expiry,now());return send({id,expiresAt:new Date(expiry).toISOString()},201);}const support=route.match(/^support-sessions\/([^/]+)$/);if(support&&method==='DELETE'){const target=owned('team.manage');const changed=this.store.db.prepare("UPDATE advancement_support_sessions SET revoked=1 WHERE id=? AND json_extract(scope,'$.organizationId')=? AND json_extract(scope,'$.projectId')=? AND COALESCE(json_extract(scope,'$.environmentId'),'')=?").run(support[1]!,target.organizationId,target.projectId,target.environmentId??'');if(!changed.changes)throw new HttpError(404,'SUPPORT_SESSION','이 환경의 지원 세션을 찾을 수 없습니다.');return send({revoked:true});}
    if(route==='usage/reconcile'&&method==='POST'){const target=owned('billing.manage'),operationId=text(input.operationId,"작업 ID",200),reservationId=text(input.reservationId,'예약 ID',100),observation=one(this.store.db,"SELECT e.amount FROM advancement_usage_entries e JOIN expansion_usage_reservations r ON r.id=? AND r.organization_id=e.organization_id AND r.project_id=e.project_id AND COALESCE(r.environment_id,'')=e.environment_id AND r.metric=e.metric WHERE e.operation_id=? AND e.organization_id=? AND e.project_id=? AND e.environment_id=? AND (e.reservation_id=r.id OR r.operation_id=e.operation_id)",reservationId,operationId,target.organizationId,target.projectId,target.environmentId??'');if(!observation)throw new HttpError(409,"USAGE_EVIDENCE_REQUIRED","같은 환경·단위·작업과 연결된 실제 사용량 근거가 아직 없습니다.");return send(this.expansion.usage.settle(target,reservationId,Number(observation.amount)));}
    throw new HttpError(404,"ADVANCEMENT_ROUTE","고도화 기능 경로를 찾을 수 없습니다.");
  }
  private parseContentInput(projectId:string,collectionId:string,recordId:string,value:unknown) {const project=this.store.project(projectId);if(!project||!project.collections?.some(item=>item.id===collectionId))throw new HttpError(404,"CONTENT_COLLECTION","컬렉션을 찾을 수 없습니다.");const parsed=parseProject({...project,collections:project.collections.map(item=>item.id===collectionId?{...item,records:[{...record(value),id:recordId}]}:item)});return parsed.collections!.find(item=>item.id===collectionId)!.records[0]!;}
  observeUsage(scope:ExpansionScope,operationId:string,metric:string,amount:number):void {const reservationId=operationId.startsWith('generation-')?operationId.slice('generation-'.length):undefined;this.expansion.usage.observe(scope,operationId,metric,amount,reservationId);}
  async recoverPendingWorkflowRuns():Promise<number>{let count=0,firstError:unknown;for(const row of many(this.store.db,"SELECT r.id,r.actor_id,w.project_id,w.environment_id FROM expansion_workflow_runs r JOIN expansion_workflows w ON w.id=r.workflow_id WHERE r.status='pending' AND NOT EXISTS(SELECT 1 FROM work_items q WHERE q.kind='workflow.run' AND json_extract(q.payload,'$.runId')=r.id) ORDER BY r.created_at LIMIT 100")){try{const scope=this.expansion.access.resolve({projectId:String(row.project_id),...(row.environment_id?{environmentId:String(row.environment_id)}:{})});this.expansion.authorizeJob(scope,String(row.actor_id),'automation.manage');await this.expansion.options.enqueueJob('workflow.run',scope,{runId:String(row.id)},'workflow-'+String(row.id),String(row.actor_id));count++;}catch(error){const terminal=error instanceof HttpError&&[401,403,404].includes(error.status);this.store.db.prepare("UPDATE expansion_workflow_runs SET status=?,error_code=?,updated_at=? WHERE id=? AND status='pending'").run(terminal?'failed':'pending',error instanceof HttpError?error.code:'WORKFLOW_RECOVERY_FAILED',now(),String(row.id));if(!terminal)firstError??=error;}}if(firstError)throw firstError;return count;}
  async syncRuntimePolicy(scope:ExpansionScope,allOrganization=false):Promise<void> {const environments=allOrganization?this.store.db.prepare("SELECT id FROM expansion_environments WHERE organization_id=?").all(scope.organizationId):[{id:scope.environmentId}];for(const row of environments){const target=this.expansion.access.environment(String(row.id)),site=await this.options.siteData(target);site.db.prepare("INSERT INTO runtime_state VALUES('advancement:policy',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(JSON.stringify({lifecycle:this.lifecycle.state(target.organizationId),flags:this.config.flags(target)}));}}
  beforeRestore(scope:ExpansionScope,site?:Store):{scope:ExpansionScope;revocations:Record<string,unknown>[];memberships:Record<string,unknown>[];accounts:Record<string,unknown>[]} {return {scope,revocations:this.store.db.prepare("SELECT * FROM advancement_auth_tombstones").all(),memberships:site?site.db.prepare("SELECT * FROM platform_memberships WHERE project_id=?").all(scope.projectId):[],accounts:site?site.db.prepare("SELECT * FROM platform_accounts").all():[]};}
  afterRestore(scope:ExpansionScope,site:Store,checkpoint?:unknown):void {site.db.prepare("DELETE FROM platform_sessions").run();site.db.prepare("DELETE FROM platform_reset_tokens").run();if(checkpoint!==undefined){const saved=record(checkpoint),owned=record(saved.scope);if(owned.projectId!==scope.projectId||owned.organizationId!==scope.organizationId||owned.dataKey!==scope.dataKey||!Array.isArray(saved.accounts)||!Array.isArray(saved.memberships))throw new HttpError(409,"RESTORE_AUTH_SCOPE","인증 복구 자료의 범위를 확인하세요.");for(const value of saved.accounts){const row=record(value);site.db.prepare("INSERT INTO platform_accounts VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email,password_hash=excluded.password_hash,display_name=excluded.display_name").run(text(row.id,"회원 ID",100),text(row.email,"회원 주소",320),text(row.password_hash,"암호 지문",500),text(row.display_name,"표시 이름",200),text(row.created_at,"생성 시각",50));}const known=new Set(saved.accounts.map(value=>text(record(value).id,"회원 ID",100)));for(const row of site.db.prepare("SELECT id FROM platform_accounts").all())if(!known.has(String(row.id)))site.db.prepare("UPDATE platform_accounts SET password_hash=?,email=?,display_name='[복원 보류]' WHERE id=?").run(randomUUID(),`restore-held-${String(row.id)}@example.invalid`,String(row.id));site.db.prepare("DELETE FROM platform_memberships WHERE project_id=?").run(scope.projectId);for(const value of saved.memberships){const row=record(value);if(one(site.db,"SELECT id FROM platform_accounts WHERE id=?",String(row.account_id)))site.db.prepare("INSERT INTO platform_memberships VALUES(?,?,?)").run(scope.projectId,text(row.account_id,"회원 ID",100),text(row.role,"역할",30));}}this.privacy.reapply(scope,site.db);this.audit.append(scope.organizationId,"system","restore.authentication.invalidate",scope.projectId);}
}
