import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,mkdir,rename} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {IncomingMessage} from 'node:http';
import {Socket} from 'node:net';
import {Store} from '../server/store';
import {ExpansionService} from '../server/expansion/service';
import {AdvancementService} from '../server/advancement/service';
import {SecurityService,totp} from '../server/advancement/security';
import {BackupService} from '../server/advancement/backups';
import {ConfigService,assertRuntimeFeature} from '../server/advancement/config';
import {AuditJournal} from '../server/advancement/audit';
import {IdentityService} from '../server/advancement/identities';
import {AdapterPolicyService,boundedProviderRequest} from '../server/advancement/adapters';
import {activeKeyId,ciphertextKeyId,decryptSecret,rotateKeyBatch} from '../server/advancement/keyring';
import {simulateWorkflow} from '../server/advancement/workflows';
import {EvidenceService} from '../server/advancement/reconciliation';
import {LifecycleService} from '../server/advancement/lifecycle';
import {PrivacyService} from '../server/advancement/privacy';
import {CatalogService} from '../server/advancement/catalog';
import {EnvironmentSecrets} from '../server/advancement/secrets';
import {ledger} from '../server/advancement/ledger';
import {packageIntegrity,parseDeclarativePackage} from '../src/domain/packages';
import {BookingExpansion} from '../server/expansion/bookings';
import {saveResource,saveSlot,createBooking,cancelBooking,saveProduct,createOrder,checkout,applyPaymentEvent} from '../server/platform/business';
import {createAccount} from '../server/platform/auth';
import {inspectPortableDatabase} from '../server/dataPortability';
import {createProject} from '../src/domain/catalog';
import {saveConnection,getConnection,enqueue,processOutbox,retryOutbox} from '../server/platform/connections';
import {one} from '../server/platform/common';
import {HttpError} from '../server/http';
import type {CreatorIdentity} from '../src/domain/expansion';
const image='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVQImWP4z8DwHwAFAAH/q842iQAAAABJRU5ErkJggg==';
const password='system-backend-password-2026';
function environment(){const names=['EXPANSION_SECRET_KEY','EXPANSION_SECRET_KEYS','EXPANSION_ACTIVE_KEY_ID','PLATFORM_ALLOWED_HOSTS','TENANT_MAIL','TENANT_SCOPED'],saved=names.map(name=>process.env[name]);process.env.EXPANSION_SECRET_KEY='1'.repeat(64);process.env.PLATFORM_ALLOWED_HOSTS='provider.example';process.env.TENANT_MAIL='test-only-credential';delete process.env.EXPANSION_SECRET_KEYS;delete process.env.EXPANSION_ACTIVE_KEY_ID;return ()=>names.forEach((name,index)=>{if(saved[index]===undefined)delete process.env[name];else process.env[name]=saved[index];});}
async function fixture(){const restore=environment(),root=await mkdtemp(path.join(tmpdir(),'automade-system-backend-')),store=new Store(path.join(root,'central.sqlite')),site=new Store(path.join(root,'site.sqlite')),expansion=new ExpansionService(store,{mode:'local',dataRoot:root,siteData:async()=>site,enqueueJob:async()=>{throw new Error('No external work in fixture');}}),account=await expansion.auth.create({email:'system-owner@example.org',password,displayName:'System owner'}),actor:CreatorIdentity={id:account.id,csrf:'test-csrf',sessionId:'test-session'},org=expansion.organizations.createOrganization(actor,false,{name:'System organization'}),workspace=expansion.organizations.createWorkspace(actor,false,{organizationId:org.id,name:'System workspace'}),project=createProject('System fixture');store.save(project);const scope=expansion.registerProject(project,workspace.id,actor),stage=expansion.organizations.createEnvironment(actor,false,{siteId:scope.siteId,name:'Staging',kind:'staging'}),staging=expansion.resolveEnvironmentScope(stage.id);return {root,store,site,expansion,actor,project,scope,staging,close(){site.close();store.close();restore();}};}
const code=(expected:string)=>(error:unknown):boolean=>error instanceof HttpError&&error.code===expected;

test('RFC 6238 vector, TOTP replay, scoped one-use stepup and recovery code enforce real authentication',async()=>{const f=await fixture();try{assert.equal(totp('GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ',59000,8),'94287082');let clock=1800000000000;const security=new SecurityService(f.store.db,()=>clock),enrollment=await security.enroll(f.actor,{password}),recovery=security.confirm(f.actor,totp(enrollment.secret,clock));assert.equal(recovery.recoveryCodes.length,10);clock+=30000;const input={password,code:totp(enrollment.secret,clock),method:'POST',path:'/api/advancement/secrets/versions',payload:{value:'unprinted-test-value'}},proof=await security.issue(f.actor,input,f.scope);await assert.rejects(security.issue(f.actor,input,f.scope),code('MFA_CODE'));assert.throws(()=>security.consume(f.actor,proof.token,input.method,input.path,f.staging,input.payload),code('STEP_UP_REQUIRED'));security.consume(f.actor,proof.token,input.method,input.path,f.scope,input.payload);assert.throws(()=>security.consume(f.actor,proof.token,input.method,input.path,f.scope,input.payload),code('STEP_UP_REQUIRED'));const recovered=await security.issue(f.actor,{...input,code:undefined,recoveryCode:recovery.recoveryCodes[0]},f.scope);assert.ok(recovered.token);await assert.rejects(security.issue(f.actor,{...input,code:undefined,recoveryCode:recovery.recoveryCodes[0]},f.scope),code('MFA_CODE'));assert.equal(security.status(f.actor).recoveryCodesRemaining,9);clock+=300001;assert.throws(()=>security.consume(f.actor,recovered.token,input.method,input.path,f.scope,input.payload),code('STEP_UP_REQUIRED'));}finally{f.close();}});

test('service identity uses its own current capabilities, exact environment and key revocation',async()=>{const f=await fixture();try{const identities=new IdentityService(f.store.db,f.expansion.access),identity=identities.create(f.scope,f.actor,false,{name:'Pipeline',capabilities:['project.read','project.edit'],expiresAt:new Date(Date.now()+3600000).toISOString()});f.store.db.prepare("UPDATE expansion_memberships SET role='member' WHERE organization_id=? AND account_id=?").run(f.scope.organizationId,f.actor.id);assert.equal(identities.authenticate(identity.token,'project.read')?.actorId,identity.id);assert.throws(()=>identities.rotate(f.staging,identity.id),code('SERVICE_IDENTITY'));assert.throws(()=>identities.authenticate(identity.token,'project.publish'),code('PERMISSION'));const next=identities.rotate(f.scope,identity.id,0);assert.equal(identities.authenticate(identity.token,'project.read'),null);assert.equal(identities.authenticate(next.token,'project.read')?.actorId,identity.id);identities.revoke(f.scope,identity.id);assert.equal(identities.authenticate(next.token,'project.read'),null);assert.ok(one(f.store.db,"SELECT 1 FROM advancement_auth_tombstones WHERE resource_id=?",identity.id));}finally{f.close();}});

test('config review CAS, kill switches and organization lifecycle remain persisted and scoped',async()=>{const f=await fixture();try{const config=new ConfigService(f.store.db,new AuditJournal(f.store.db)),review=config.preview(f.staging,f.actor.id,{baseRevision:1,config:{siteUrl:'https://staging.example'}});assert.throws(()=>config.apply(f.scope,f.actor.id,review.id,review.approvalFingerprint),code('CONFIG_REVIEW'));assert.equal(config.apply(f.staging,f.actor.id,review.id,review.approvalFingerprint).revision,2);assert.equal(config.apply(f.staging,f.actor.id,review.id,review.approvalFingerprint).revision,2);config.flag(f.staging,f.actor.id,'publication',{baseRevision:0,enabled:false,reason:'검수 중지'});assert.throws(()=>config.assertEnabled(f.staging,'publication'),code('FEATURE_PAUSED'));config.assertEnabled(f.scope,'publication');const lifecycle=new LifecycleService(f.store.db);lifecycle.change(f.scope,{baseRevision:0,state:'archived',reason:'보관'});assert.throws(()=>config.assertLifecycle(f.staging),code('ORGANIZATION_ARCHIVED'));f.site.db.prepare("INSERT INTO runtime_state VALUES('advancement:policy',?)").run(JSON.stringify({lifecycle:lifecycle.state(f.scope.organizationId),flags:config.flags(f.scope)}));assert.throws(()=>assertRuntimeFeature(f.site.db,'paid-actions'),code('ORGANIZATION_ARCHIVED'));assert.throws(()=>lifecycle.change(f.scope,{baseRevision:0,state:'active',reason:'stale'}),code('LIFECYCLE_CONFLICT'));}finally{f.close();}});

test('asset quarantine, explicit public approval, derivative receipts and private publication are enforced',async()=>{const f=await fixture();try{const blob=await f.expansion.blobs.upload(f.scope,{dataUrl:image,alt:'원본',license:'직접 제작',requestKey:'original-1'});assert.equal(blob.inspection?.state,'quarantined');assert.equal(blob.inspection?.inspection.malwareScan,'not-configured');assert.throws(()=>f.expansion.blobs.assertPublishable(f.project.id,[blob.id]),code('ASSET_PUBLICATION_REQUIRED'));const replay=await f.expansion.blobs.upload(f.scope,{dataUrl:image,alt:'원본',license:'직접 제작',requestKey:'original-1'});assert.equal(replay.id,blob.id);await assert.rejects(f.expansion.blobs.upload(f.scope,{dataUrl:image,alt:'다른 설명',license:'직접 제작',requestKey:'original-1'}),code('ASSET_UPLOAD_CONFLICT'));const privateAsset=await f.expansion.blobs.approve(f.scope,blob.id,{baseRevision:1,state:'approved',visibility:'private',reason:'내부 검수'},f.actor.id);assert.equal(privateAsset.inspection?.visibility,'private');await assert.rejects(f.expansion.resolveBlob(f.project.id,blob.id),code('ASSET_PUBLICATION_REQUIRED'));await f.expansion.blobs.approve(f.scope,blob.id,{baseRevision:2,state:'approved',visibility:'public',reason:'공개 사용권 검토'},f.actor.id);assert.ok((await f.expansion.resolveBlob(f.project.id,blob.id)).startsWith('data:image/png;'));const variant=await f.expansion.blobs.upload(f.scope,{sourceRef:blob.id,variantKey:'preview',dataUrl:image,alt:'변형',license:'직접 제작'}),again=await f.expansion.blobs.upload(f.scope,{sourceRef:blob.id,variantKey:'preview',dataUrl:image,alt:'변형',license:'직접 제작'});assert.equal(again.id,variant.id);assert.equal(variant.inspection?.sourceRef,blob.id);assert.equal(variant.inspection?.state,'quarantined');await assert.rejects(f.expansion.blobs.approve(f.scope,blob.id,{baseRevision:1,state:'approved',visibility:'public',reason:'stale'},f.actor.id),code('ASSET_APPROVAL_CONFLICT'));}finally{f.close();}});

test('backup captures snapshot references and key IDs under the same freeze, then checks exact environment and integrity',async()=>{const f=await fixture();try{const blob=await f.expansion.blobs.upload(f.scope,{dataUrl:image,alt:'백업 원본',license:'직접 제작'});f.expansion.secrets.save(f.scope.organizationId,f.actor.id,{name:'TENANT_BACKUP',value:'snapshot-secret'});const original=f.store.snapshot.bind(f.store);f.store.snapshot=(file:string)=>{original(file);f.expansion.blobs.remove(f.scope,blob.id);process.env.EXPANSION_SECRET_KEYS=JSON.stringify({next:'2'.repeat(64)});process.env.EXPANSION_ACTIVE_KEY_ID='next';rotateKeyBatch(f.store.db,'after-snapshot');};const backups=new BackupService(f.store,f.expansion,f.root);let frozen=false;const backup=await backups.create(f.scope,f.site,async(_scope,work)=>{frozen=true;const result=await work(f.site);assert.equal(result,undefined);assert.equal(frozen,true);frozen=false;return result;});assert.equal(backup.consistency,'scoped-freeze');assert.deepEqual(backup.keyIds,['legacy']);assert.equal(backup.files.filter(item=>item.kind==='blob').length,1);assert.equal((await backups.verify(f.scope,backup.id)).state,'verified');await assert.rejects(backups.verify(f.staging,backup.id),code('BACKUP_SET'));const rehearsal=await backups.rehearse(f.scope,backup.id);assert.equal(rehearsal.databaseChecks,2);const file=path.join(backups.root,backup.id,'blobs',blob.sha256),bytes=await readFile(file);await writeFile(file,Buffer.concat([bytes,Buffer.from('tamper')]));await assert.rejects(backups.verify(f.scope,backup.id),code('BACKUP_INTEGRITY'));}finally{f.close();}});

test('backup set captures scoped artifact and runtime bytes, rehearses them and restores absent exports without overwrite',async()=>{const f=await fixture();try{const exportRoot=path.join(f.root,'exports'),directory=path.join(exportRoot,'release-backup');await mkdir(path.join(directory,'runtime'),{recursive:true});await writeFile(path.join(directory,'server.mjs'),'export const fixture = true;');await writeFile(path.join(directory,'runtime','node.exe'),'runtime-byte-fixture');await writeFile(path.join(directory,'.env'),'private-fixture-not-exported');await writeFile(path.join(directory,'.site-data.sqlite'),'private-db-fixture-not-exported');f.store.db.prepare("INSERT INTO exports VALUES('release-backup',?,?,'ready','2026-10-08',NULL)").run(f.project.id,directory);f.store.db.prepare("INSERT INTO runtime_state VALUES('generation:scope:release-backup',?)").run(JSON.stringify(f.scope));const backups=new BackupService(f.store,f.expansion,f.root,exportRoot),backup=await backups.create(f.scope,f.site,async(_scope,work)=>work(f.site));assert.equal(backup.artifacts?.length,1);assert.ok(backup.artifacts![0]!.files.some(file=>file.path==='runtime/node.exe'));assert.ok(backup.artifacts![0]!.files.every(file=>!file.path.startsWith('.env')&&!file.path.includes('site-data')));assert.equal((await backups.rehearse(f.scope,backup.id)).artifactChecks,1);assert.equal((await backups.restoreArtifacts(f.scope,backup.id)).preserved,1);await rename(directory,directory+'-fixture-saved');assert.equal((await backups.restoreArtifacts(f.scope,backup.id)).restored,1);assert.equal(await readFile(path.join(directory,'runtime','node.exe'),'utf8'),'runtime-byte-fixture');await writeFile(path.join(directory,'server.mjs'),'changed-current-export');await assert.rejects(backups.restoreArtifacts(f.scope,backup.id),code('BACKUP_ARTIFACT_CONFLICT'));await writeFile(path.join(backups.root,backup.id,backup.artifacts![0]!.backupDirectory,'server.mjs'),'changed-backup');await assert.rejects(backups.verify(f.scope,backup.id),code('BACKUP_ARTIFACT_HASH'));}finally{f.close();}});

test('master-key rotation resumes bounded batches, includes pending MFA secrets and fixes target per job',async()=>{const f=await fixture();try{f.expansion.secrets.save(f.scope.organizationId,f.actor.id,{name:'TENANT_FIRST',value:'first'});f.expansion.secrets.save(f.scope.organizationId,f.actor.id,{name:'TENANT_SECOND',value:'second'});await new SecurityService(f.store.db).enroll(f.actor,{password});process.env.EXPANSION_SECRET_KEYS=JSON.stringify({next:'2'.repeat(64)});process.env.EXPANSION_ACTIVE_KEY_ID='next';assert.equal(activeKeyId(),'next');const first=rotateKeyBatch(f.store.db,'rotation-1',1);assert.equal(first.processed,1);assert.equal(first.remaining,2);const second=rotateKeyBatch(f.store.db,'rotation-1',10);assert.equal(second.remaining,0);assert.equal(second.status,'completed');assert.equal(ciphertextKeyId(String(one(f.store.db,'SELECT pending_secret FROM advancement_mfa WHERE account_id=?',f.actor.id)?.pending_secret)),'next');for(const row of f.store.db.prepare('SELECT ciphertext FROM expansion_secrets').all())assert.ok(['first','second'].includes(decryptSecret(String(row.ciphertext))));process.env.EXPANSION_ACTIVE_KEY_ID='legacy';assert.throws(()=>rotateKeyBatch(f.store.db,'rotation-1'),code('KEY_ROTATION_TARGET'));}finally{f.close();}});

test('adapter retries only declared idempotent writes; unknown delivery and late lease recovery stay held',async()=>{const f=await fixture();try{const id=String(saveConnection(f.site.db,f.project.id,{name:'Mail',kind:'mail',endpoint:'https://provider.example/mail',allowedHost:'provider.example',secretRef:'TENANT_MAIL'}).id),connection=getConnection(f.site.db,id);let calls=0;await assert.rejects(boundedProviderRequest(f.site.db,connection,'POST',{},'once',async()=>{calls++;throw new HttpError(503,'PROVIDER_RETRYABLE','fixture');}),code('PROVIDER_RETRYABLE'));assert.equal(calls,1);const policy=new AdapterPolicyService(f.site.db);policy.save(f.project.id,id,{baseRevision:0,capabilities:{idempotentWrites:true,maxRetries:1}});calls=0;assert.deepEqual(await boundedProviderRequest(f.site.db,connection,'POST',{},'twice',async()=>{calls++;if(calls===1)throw new HttpError(503,'PROVIDER_RETRYABLE','fixture');return {accepted:true};}),{accepted:true});assert.equal(calls,2);policy.save(f.project.id,id,{baseRevision:1,capabilities:{idempotentWrites:false}});const unknown=enqueue(f.site.db,f.project.id,id,'unknown',{message:'ambiguous'});await processOutbox(f.site.db,async()=>{throw new HttpError(502,'PROVIDER_CONNECTION','lost response');});assert.equal(one(f.site.db,'SELECT error_code FROM platform_outbox WHERE id=?',unknown)?.error_code,'EXTERNAL_RESULT_UNKNOWN');assert.throws(()=>retryOutbox(f.site.db,f.project.id,unknown),code('UNKNOWN_EVIDENCE_REQUIRED'));const crashed=enqueue(f.site.db,f.project.id,id,'crash',{message:'sent before exit'});f.site.db.prepare("UPDATE platform_outbox SET status='sending',lease_until=0 WHERE id=?").run(crashed);calls=0;await processOutbox(f.site.db,async()=>{calls++;return {};});assert.equal(calls,0);assert.equal(one(f.site.db,'SELECT error_code FROM platform_outbox WHERE id=?',crashed)?.error_code,'EXTERNAL_RESULT_UNKNOWN');}finally{f.close();}});

test('workflow simulation does not write or enqueue, and unknown retry requires server evidence',async()=>{const f=await fixture();try{const workflow=f.expansion.workflows.save(f.scope,f.actor.id,{name:'dry run',trigger:'manual',enabled:true,conditions:[{field:'amount',operator:'greaterThan',value:2}],actions:[{type:'submission.update',status:'completed'}]}),before=Number(one(f.store.db,'SELECT COUNT(*) AS n FROM expansion_workflow_runs')?.n),result=simulateWorkflow(workflow,{amount:3},f.site.db);assert.equal(result.matched,true);assert.equal(result.externalEffects,false);assert.equal(Number(one(f.store.db,'SELECT COUNT(*) AS n FROM expansion_workflow_runs')?.n),before);const evidence=new EvidenceService(f.store.db),review=evidence.create(f.scope,{kind:'work',targetId:'external-work'});assert.throws(()=>evidence.assertRetry(f.scope,'external-work'),code('UNKNOWN_EVIDENCE_REQUIRED'));await assert.rejects(evidence.verify(f.scope,review.id,1,f.site.db,()=>{}),code('EVIDENCE_PROVIDER_REQUIRED'));await evidence.verify(f.scope,review.id,1,f.site.db,()=>{},async()=>({source:'configured-status-adapter-fixture',resolution:'no-effect',evidence:{targetId:'external-work',status:'absent'}}));evidence.assertRetry(f.scope,'external-work');await assert.rejects(evidence.verify(f.scope,review.id,1,f.site.db,()=>{},async()=>({source:'fixture',resolution:'no-effect',evidence:{}})),code('RECONCILIATION_CONFLICT'));}finally{f.close();}});

test('usage observations preserve expired actual spend without double counting and isolate environment settlements',async()=>{const f=await fixture();try{const usage=f.expansion.usage;usage.limit(f.scope.organizationId,{metric:'generations',amount:2});const reservation=usage.reserve(f.scope,'generations',1,'reserved-before-exit');f.store.db.prepare('UPDATE expansion_usage_reservations SET expires_at=0 WHERE id=?').run(reservation.id);assert.equal(usage.list(f.scope).find(item=>item.id===reservation.id)?.status,'expired');usage.observe(f.scope,'generation-attempt','generations',1,reservation.id);usage.observe(f.scope,'generation-attempt','generations',1,reservation.id);assert.equal(usage.list(f.scope).find(item=>item.id===reservation.id)?.status,'committed');assert.equal(Number(usage.budget(f.scope.organizationId).find(row=>row.metric==='generations')?.used),1);assert.throws(()=>usage.settle(f.staging,reservation.id,1),code('USAGE_RESERVATION'));assert.equal(usage.evidence(f.staging).actual.length,0);usage.recordCost(f.scope,{kind:'estimate',operationId:'generation-attempt',amountMinor:100,currency:'KRW',source:'configured-estimate-fixture',evidenceHash:'a'.repeat(64)});assert.equal(usage.evidence(f.scope).costs[0]?.kind,'estimate');assert.equal(usage.evidence(f.scope).actual.length,1);usage.observe(f.scope,'storage-first','storageBytes',200);usage.observe(f.scope,'storage-second','storageBytes',120);usage.observe(f.staging,'storage-stage','storageBytes',300);const storage=usage.evidence(f.scope).aggregate.find(row=>row.metric==='storageBytes');assert.equal(storage?.amount,120);assert.equal(storage?.mode,'latest-snapshot');assert.equal(usage.evidence(f.scope).aggregate.find(row=>row.metric==='generations')?.amount,1);assert.equal(usage.evidence(f.staging).aggregate.find(row=>row.metric==='storageBytes')?.amount,300);}finally{f.close();}});

test('pending workflow recovery records revoked actor failure and still enqueues later authorized runs',async()=>{const f=await fixture();try{const workflow=f.expansion.workflows.save(f.scope,f.actor.id,{name:'recovery',trigger:'manual',enabled:true,conditions:[],actions:[{type:'submission.update',status:'completed'}]}),revoked=f.expansion.workflows.events(f.scope,'manual',{},'revoked-first',f.actor.id)[0]!,valid=f.expansion.workflows.events(f.scope,'manual',{},'valid-second',f.actor.id)[0]!;assert.ok(workflow.id);f.store.db.prepare("UPDATE expansion_workflow_runs SET actor_id='revoked-actor',created_at='2000-01-01' WHERE id=?").run(revoked);const enqueued:string[]=[];f.expansion.options.enqueueJob=async(_kind,_scope,payload)=>{enqueued.push(String((payload as {runId:string}).runId));return {id:'recovered-job',status:'queued'};};const advancement=new AdvancementService(f.store,f.expansion,{dataRoot:f.root,siteData:async()=>f.site});assert.equal(await advancement.recoverPendingWorkflowRuns(),1);assert.deepEqual(enqueued,[valid]);assert.equal(one(f.store.db,'SELECT status,error_code FROM expansion_workflow_runs WHERE id=?',revoked)?.status,'failed');assert.equal(one(f.store.db,'SELECT error_code FROM expansion_workflow_runs WHERE id=?',revoked)?.error_code,'JOB_ACTOR');}finally{f.close();}});

test('environment secret registration fails closed until tested and activated without changing production',async()=>{const f=await fixture();try{f.expansion.secrets.save(f.scope.organizationId,f.actor.id,{name:'TENANT_SCOPED',value:'legacy-production'});assert.equal(f.expansion.secrets.resolve(f.scope,'TENANT_SCOPED'),'legacy-production');process.env.TENANT_SCOPED='wrong-process-fallback';const versions=new EnvironmentSecrets(f.store.db),registered=versions.register(f.staging,{name:'TENANT_SCOPED',value:'staging-only'});assert.equal(f.expansion.secrets.resolve(f.staging,'TENANT_SCOPED'),undefined);assert.equal(f.expansion.secrets.resolve(f.scope,'TENANT_SCOPED'),'legacy-production');const connection=saveConnection(f.site.db,f.project.id,{name:'Secret validation',kind:'mail',endpoint:'https://provider.example/verify',allowedHost:'provider.example',secretRef:'TENANT_SCOPED'});f.expansion.configureRuntime(f.staging,f.site);assert.throws(()=>getConnection(f.site.db,String(connection.id)).resolveSecret?.('TENANT_SCOPED'),code('SECRET_INACTIVE'));await assert.rejects(f.expansion.runtimeSecrets(f.staging,f.site),code('SECRET_INACTIVE'));await versions.test(f.staging,registered.id,f.site.db,String(connection.id),()=>{},async(value)=>{assert.equal(value.resolveSecret?.('TENANT_SCOPED'),'staging-only');return {reachable:true};});versions.activate(f.staging,registered.id,f.site.db);assert.equal(f.expansion.secrets.resolve(f.staging,'TENANT_SCOPED'),'staging-only');assert.equal(f.expansion.secrets.resolve(f.scope,'TENANT_SCOPED'),'legacy-production');assert.throws(()=>versions.retire(f.staging,registered.id),code('SECRET_ACTIVE'));}finally{f.close();}});

test('support delegation expires and is withdrawn when its approving administrator loses authority',async()=>{const f=await fixture();try{const account=await f.expansion.auth.create({email:'support@example.org',password,displayName:'Support'}),support:CreatorIdentity={id:account.id,sessionId:'support-session',csrf:'support-csrf'};f.store.db.prepare("INSERT INTO expansion_memberships VALUES(?,?,'member')").run(f.scope.organizationId,support.id);f.store.db.prepare("INSERT INTO advancement_support_sessions VALUES('support-proof',?,?,?,'[\"project.read\"]','support review',?,0,'now')").run(JSON.stringify(f.staging),support.id,f.actor.id,Date.now()+60000);assert.doesNotThrow(()=>f.expansion.access.authorize(support,f.staging,'project.read'));assert.throws(()=>f.expansion.access.authorize(support,f.scope,'project.read'),code('PERMISSION'));f.store.db.prepare("UPDATE expansion_memberships SET role='member' WHERE organization_id=? AND account_id=?").run(f.scope.organizationId,f.actor.id);assert.throws(()=>f.expansion.access.authorize(support,f.staging,'project.read'),code('PERMISSION'));f.store.db.prepare("UPDATE expansion_memberships SET role='owner' WHERE organization_id=? AND account_id=?").run(f.scope.organizationId,f.actor.id);f.store.db.prepare("UPDATE advancement_support_sessions SET expires_at=0 WHERE id='support-proof'").run();assert.throws(()=>f.expansion.access.authorize(support,f.staging,'project.read'),code('PERMISSION'));}finally{f.close();}});

test('organization handoff needs recipient acceptance and closing revokes machine and support access',async()=>{const f=await fixture();try{const account=await f.expansion.auth.create({email:'next-owner@example.org',password,displayName:'Next owner'}),next:CreatorIdentity={id:account.id,sessionId:'next-owner-session',csrf:'next-owner-csrf'};f.store.db.prepare("INSERT INTO expansion_memberships VALUES(?,?,'member')").run(f.scope.organizationId,next.id);const lifecycle=new LifecycleService(f.store.db),proposal=lifecycle.propose(f.scope,f.actor,next.id);assert.equal(f.expansion.access.role(f.actor.id,f.scope.organizationId),'owner');assert.throws(()=>lifecycle.accept(f.scope,f.actor,proposal.id),code('HANDOFF_EXPIRED'));lifecycle.accept(f.scope,next,proposal.id);assert.equal(f.expansion.access.role(next.id,f.scope.organizationId),'owner');assert.equal(f.expansion.access.role(f.actor.id,f.scope.organizationId),'admin');const identity=new IdentityService(f.store.db,f.expansion.access).create(f.scope,next,false,{name:'Closing service',capabilities:['project.read'],expiresAt:new Date(Date.now()+60000).toISOString()});lifecycle.change(f.scope,{baseRevision:0,state:'closing',reason:'retirement review'});assert.equal(new IdentityService(f.store.db,f.expansion.access).authenticate(identity.token,'project.read'),null);}finally{f.close();}});

test('catalog approval and revocation block new installation and publication of a known version',async()=>{const f=await fixture();try{const source={id:'system.test-pack',name:'Declarative pack',version:'1.0.0',protocol:1,definitions:[{id:'intro',name:'Introduction',description:'Safe text',template:'text',defaults:{title:'Intro'}}]},manifest=parseDeclarativePackage({...source,integrity:await packageIntegrity(source)}),catalog=new CatalogService(f.store.db),entry=await catalog.submit(f.scope,f.actor.id,{manifest,license:'MIT',supportContact:'support@example.org',evidence:'Local contract test'},()=>{});assert.throws(()=>catalog.assertInstall(manifest.id,manifest.version),code('CATALOG_UNAVAILABLE'));assert.throws(()=>catalog.review(f.scope,f.actor.id,entry.id,{status:'approved',evidence:'Self review'}),code('CATALOG_SELF_REVIEW'));catalog.review(f.scope,'central-reviewer',entry.id,{status:'approved',evidence:'Local approval fixture'});catalog.assertInstall(manifest.id,manifest.version);catalog.review(f.scope,'central-reviewer',entry.id,{status:'revoked',evidence:'Contract withdrawn'});assert.throws(()=>catalog.assertInstall(manifest.id,manifest.version),code('CATALOG_UNAVAILABLE'));f.project.blockPackages=[manifest];assert.throws(()=>f.expansion.assertPublication(f.scope,f.project),code('CATALOG_UNAVAILABLE'));}finally{f.close();}});

test('order ledger records authoritative first refund status once and ignores older payment events',async()=>{const f=await fixture();try{const buyer=await createAccount(f.site.db,{email:'ledger@example.org',password,displayName:'Buyer'}),product=saveProduct(f.site.db,f.project.id,{name:'Product',priceMinor:1000,currency:'KRW',inventory:2}),order=createOrder(f.site.db,f.project.id,String(buyer.id),{items:[{productId:product.id,quantity:1}],idempotencyKey:'ledger-order'}),connection=saveConnection(f.site.db,f.project.id,{name:'Payment proof',kind:'payment',endpoint:'https://provider.example/pay',allowedHost:'provider.example',secretRef:'TENANT_MAIL',webhookSecretRef:'TENANT_MAIL'});await checkout(f.site.db,String(order.id),String(connection.id),async()=>({paymentId:'payment-proof',checkoutUrl:'https://provider.example/checkout'}));const proof={eventId:'partial-first',orderId:order.id,paymentId:'payment-proof',amountMinor:1000,currency:'KRW',status:'partially_refunded',refundedMinor:300,sequence:2};applyPaymentEvent(f.site.db,String(connection.id),proof);applyPaymentEvent(f.site.db,String(connection.id),proof);applyPaymentEvent(f.site.db,String(connection.id),{...proof,eventId:'older-paid',status:'paid',refundedMinor:0,sequence:1});const entries=ledger(f.site.db,f.project.id,'orders').items;assert.equal(entries.filter(row=>row.kind==='payment_confirmed').length,1);assert.equal(entries.filter(row=>row.kind==='payment_confirmed').reduce((sum,row)=>sum+row.amountMinor,0),1000);assert.equal(entries.filter(row=>row.kind==='refund_confirmed').reduce((sum,row)=>sum+row.amountMinor,0),300);assert.equal(one(f.site.db,'SELECT status,refunded_minor FROM platform_orders WHERE id=?',String(order.id))?.status,'partially_refunded');assert.equal(ledger(f.site.db,f.project.id,'subscriptions').items.length,0);}finally{f.close();}});

test('portable DB version 15 rejects central key-rotation records and modified seed organization realms',async()=>{const f=await fixture();try{const copy=path.join(f.root,'portable.sqlite');f.site.snapshot(copy);assert.equal((await inspectPortableDatabase(copy,f.project.id)).migrations.length,15);const imported=new Store(copy);imported.db.prepare("INSERT INTO advancement_key_rotation VALUES('rotation','legacy','completed',0,'now','now')").run();imported.close();await assert.rejects(inspectPortableDatabase(copy,f.project.id),code('DATABASE_REALM'));}finally{f.close();}});

test('timezone recurrence materializes DST gap/fold choices with UTC and resolver provenance',async()=>{const f=await fixture();try{const business=new BookingExpansion(f.site.db),resource=saveResource(f.site.db,f.project.id,{name:'Wall time resource',capacity:2}),gap={resourceId:resource.id,name:'DST gap',startDate:'2027-03-14',endDate:'2027-03-14',weekdays:[0],startTime:'02:30',durationMinutes:30,timeZone:'America/New_York',capacity:2};assert.throws(()=>business.saveRule(f.project.id,gap),/존재하지 않는/);const shifted=business.saveRule(f.project.id,{...gap,gapPolicy:'shift-forward'});assert.equal(business.materialize(f.project.id,shifted.id).created,1);assert.equal(business.materialize(f.project.id,shifted.id).created,0);const source=one(f.site.db,'SELECT s.starts_at,p.* FROM platform_slots s JOIN advancement_booking_slot_provenance p ON p.slot_id=s.id WHERE p.rule_id=?',shifted.id)!;assert.equal(source.starts_at,'2027-03-14T07:30:00.000Z');assert.equal(source.wall_time,'2027-03-14T02:30:00');assert.equal(source.shifted,1);assert.equal(source.resolver_version,'intl-offset-v1');assert.equal(source.icu_version,process.versions.icu);const fold=business.saveRule(f.project.id,{...gap,name:'DST fold',startDate:'2026-11-01',endDate:'2026-11-01',startTime:'01:30',disambiguation:'later'});assert.equal(business.materialize(f.project.id,fold.id).created,1);assert.equal(one(f.site.db,'SELECT s.starts_at FROM platform_slots s JOIN advancement_booking_slot_provenance p ON p.slot_id=s.id WHERE p.rule_id=?',fold.id)?.starts_at,'2026-11-01T06:30:00.000Z');}finally{f.close();}});

test('capacity review binds confirmed bookings and offers, detects concurrent changes and preserves slot time',async()=>{const f=await fixture();try{const resource=saveResource(f.site.db,f.project.id,{name:'Capacity resource',capacity:2}),visitor=await createAccount(f.site.db,{email:'capacity@example.org',password,displayName:'Visitor'}),start=new Date(Date.now()+86400000).toISOString(),end=new Date(Date.now()+90000000).toISOString(),slot=saveSlot(f.site.db,f.project.id,{resourceId:resource.id,startsAt:start,endsAt:end,capacity:2}),business=new BookingExpansion(f.site.db);assert.throws(()=>saveResource(f.site.db,f.project.id,{id:resource.id,name:'Capacity resource',capacity:1}),code('BOOKING_REVIEW_REQUIRED'));const review=business.previewChange(f.project.id,{kind:'resource',targetId:resource.id,input:{name:'Capacity resource',capacity:1,active:true}});const booking=createBooking(f.site.db,f.project.id,String(visitor.id),{slotId:slot.id,quantity:2,idempotencyKey:'after-review'});assert.throws(()=>business.applyChange(f.project.id,review.id,review.approvalFingerprint),code('BOOKING_REVIEW_STALE'));const conflict=business.previewChange(f.project.id,{kind:'resource',targetId:resource.id,input:{name:'Capacity resource',capacity:1,active:true}});assert.ok(conflict.conflicts.includes('CONFIRMED_OR_OFFERED_CAPACITY'));assert.throws(()=>business.applyChange(f.project.id,conflict.id,conflict.approvalFingerprint),code('BOOKING_REVIEW_CONFLICT'));cancelBooking(f.site.db,String(booking.id));const cleared=business.previewChange(f.project.id,{kind:'resource',targetId:resource.id,input:{name:'Capacity resource',capacity:1,active:true}});assert.equal(business.applyChange(f.project.id,cleared.id,cleared.approvalFingerprint).applied,true);assert.equal(business.applyChange(f.project.id,cleared.id,cleared.approvalFingerprint).applied,true);assert.equal(one(f.site.db,'SELECT capacity,starts_at FROM platform_slots WHERE id=?',String(slot.id))?.capacity,1);assert.equal(one(f.site.db,'SELECT starts_at FROM platform_slots WHERE id=?',String(slot.id))?.starts_at,start);}finally{f.close();}});

test('privacy requests and restore erasure markers bind exact environment without crossing visitor databases',async()=>{const f=await fixture();try{const privacy=new PrivacyService(f.store.db),visitor=await createAccount(f.site.db,{email:'privacy@example.org',password,displayName:'Private visitor'});f.site.db.prepare("INSERT INTO platform_memberships VALUES(?,?,'visitor')").run(f.project.id,String(visitor.id));const request=privacy.create(f.scope,f.site.db,{subjectId:visitor.id,action:'anonymize'});assert.equal(privacy.list(f.staging).length,0);assert.throws(()=>privacy.run(f.staging,request.id,f.site.db),code('PRIVACY_REQUEST'));const outcome=privacy.run(f.scope,request.id,f.site.db);assert.equal(outcome.request.heldReason,'UNSTRUCTURED_PAYLOAD_REVIEW_REQUIRED');f.site.db.prepare("UPDATE platform_accounts SET email='restored@example.org',display_name='Old restore' WHERE id=?").run(String(visitor.id));privacy.reapply(f.staging,f.site.db);assert.equal(one(f.site.db,'SELECT email FROM platform_accounts WHERE id=?',String(visitor.id))?.email,'restored@example.org');privacy.reapply(f.scope,f.site.db);assert.match(String(one(f.site.db,'SELECT email FROM platform_accounts WHERE id=?',String(visitor.id))?.email),/^masked-/);}finally{f.close();}});

test('managed request rejects legacy team writes without stepup while local owner remains authorized',async()=>{const f=await fixture();try{const managed=new ExpansionService(f.store,{mode:'managed',dataRoot:f.root,siteData:async()=>f.site,enqueueJob:async()=>{throw new Error('not invoked');}}),advancement=new AdvancementService(f.store,managed,{dataRoot:f.root,siteData:async()=>f.site}),req=new IncomingMessage(new Socket());req.method='POST';req.headers={};const url=new URL('http://localhost/api/expansion/invites');assert.throws(()=>advancement.assertRequest(req,url,{creator:f.actor,localOwner:false,input:{organizationId:f.scope.organizationId}}),code('STEP_UP_REQUIRED'));for(const route of ['/api/platform/connections','/api/platform/orders/order-fixture/refund'])assert.throws(()=>advancement.assertRequest(req,new URL('http://localhost'+route),{creator:f.actor,localOwner:false,scope:f.scope,input:{}}),code('STEP_UP_REQUIRED'));const local=new AdvancementService(f.store,f.expansion,{dataRoot:f.root,siteData:async()=>f.site});assert.doesNotThrow(()=>local.assertRequest(req,url,{creator:null,localOwner:true,input:{organizationId:f.scope.organizationId}}));req.socket.destroy();}finally{f.close();}});
