import {DatabaseSync} from 'node:sqlite';
import {createHash,randomUUID} from 'node:crypto';
import {mkdir,realpath,rename} from 'node:fs/promises';
import path from 'node:path';
import type {ExpansionScope} from '../src/domain/expansion';
import type {Store} from './store';
import type {OperationsService} from './operationsService';
import {inspectPortableDatabase} from './dataPortability';
import {contained,HttpError} from './http';
import {record} from '../src/domain/validation';
import {transaction} from './platform/common';
interface MigrationBody {requestKey:string;fingerprint:string;originalFile:string;shadowFile:string;counts:Record<string,number>;hashes:Record<string,string>;sourceConfigRevision:number;target:'sqlite-local';reverseOriginalBackup?:string}
export function databaseInventory(db:DatabaseSync):{counts:Record<string,number>;hashes:Record<string,string>}{
 const counts:Record<string,number>={},hashes:Record<string,string>={};for(const table of db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all()){const name=String(table.name);if(!/^[a-z][a-z0-9_]+$/.test(name))throw new HttpError(422,'MIGRATION_SCHEMA','지원하는 테이블 이름이 아닙니다.');const columns=db.prepare(`PRAGMA table_info("${name}")`).all(),keys=columns.filter(column=>Number(column.pk)>0).sort((a,b)=>Number(a.pk)-Number(b.pk)).map(column=>String(column.name));for(const key of keys)if(!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(key))throw new HttpError(422,'MIGRATION_SCHEMA','지원하는 열 이름이 아닙니다.');const order=keys.length?keys.map(key=>`"${key}"`).join(','):'rowid',hash=createHash('sha256');let count=0;for(const row of db.prepare(`SELECT * FROM "${name}" ORDER BY ${order}`).iterate()){hash.update(JSON.stringify(row)+'\n');count++;}counts[name]=count;hashes[name]=hash.digest('hex');}return {counts,hashes};
}
export class StorageMigrationService {
 constructor(readonly store:Store,readonly operations:OperationsService,readonly dataRoot:string){}
 private row(scope:ExpansionScope,id:string){const row=this.store.db.prepare('SELECT * FROM system_storage_migrations WHERE id=? AND json_extract(scope,\'$.projectId\')=? AND json_extract(scope,\'$.environmentId\')=?').get(id,scope.projectId,scope.environmentId??null);if(!row)throw new HttpError(404,'STORAGE_MIGRATION','선택한 환경의 이전 작업이 없습니다.');return {state:String(row.state),body:JSON.parse(String(row.body)) as MigrationBody};}
 list(scope:ExpansionScope){return this.store.db.prepare('SELECT id,state,body,created_at,updated_at FROM system_storage_migrations WHERE json_extract(scope,\'$.projectId\')=? AND json_extract(scope,\'$.environmentId\')=? ORDER BY created_at DESC LIMIT 100').all(scope.projectId,scope.environmentId??null).map(row=>{const body=JSON.parse(String(row.body)) as MigrationBody;return {id:String(row.id),state:String(row.state),target:body.target,counts:body.counts,sourceConfigRevision:body.sourceConfigRevision,createdAt:Number(row.created_at),updatedAt:Number(row.updated_at),externalProviders:'not-configured'};});}
 async create(scope:ExpansionScope,input:Record<string,unknown>,authorize:()=>void){if(input.target!=='sqlite-local'||typeof input.requestKey!=='string'||!/^[a-zA-Z0-9_-]{1,100}$/.test(input.requestKey)||!scope.environmentId)throw new HttpError(400,'STORAGE_TARGET','로컬 SQLite 이전 대상과 환경·요청 키를 지정하세요.');authorize();const fingerprint=createHash('sha256').update(JSON.stringify([scope,input.target,input.expectedConfigRevision])).digest('hex'),existing=this.store.db.prepare('SELECT id,body FROM system_storage_migrations WHERE json_extract(scope,\'$.projectId\')=? AND json_extract(scope,\'$.environmentId\')=? AND json_extract(body,\'$.requestKey\')=?').get(scope.projectId,scope.environmentId,input.requestKey);if(existing){if(record(JSON.parse(String(existing.body))).fingerprint!==fingerprint)throw new HttpError(409,'STORAGE_IDEMPOTENCY','같은 이전 요청 키의 내용이 다릅니다.');return this.list(scope).find(row=>row.id===existing.id);}
 const config=this.store.db.prepare('SELECT config_version FROM expansion_environments WHERE id=?').get(scope.environmentId);if(Number(config?.config_version)!==input.expectedConfigRevision)throw new HttpError(409,'CONFIG_CONFLICT','검토한 환경 설정 버전이 다릅니다.');const originalFile=await this.operations.currentScopeFile(scope),id=randomUUID(),folder=path.join(this.dataRoot,'storage-migrations',id);await mkdir(folder,{recursive:true});if(!contained(await realpath(this.dataRoot),await realpath(folder)))throw new HttpError(403,'STORAGE_PATH','관리되는 저장소 경로만 사용할 수 있습니다.');const shadowFile=path.join(folder,'shadow.sqlite');
 await this.operations.withScopeFreeze(scope,async source=>{authorize();if(Number(this.store.db.prepare('SELECT config_version FROM expansion_environments WHERE id=?').get(scope.environmentId!)?.config_version)!==input.expectedConfigRevision)throw new HttpError(409,'CONFIG_CONFLICT','Configuration changed during preparation');source.snapshot(shadowFile);await inspectPortableDatabase(shadowFile,scope.projectId);const inventory=databaseInventory(source.db),shadow=new DatabaseSync(shadowFile,{readOnly:true});try{if(JSON.stringify(databaseInventory(shadow))!==JSON.stringify(inventory))throw new HttpError(409,'STORAGE_SHADOW','복사된 데이터 건수·내용이 다릅니다.');}finally{shadow.close();}const body:MigrationBody={requestKey:String(input.requestKey),fingerprint,originalFile,shadowFile,...inventory,sourceConfigRevision:Number(input.expectedConfigRevision),target:'sqlite-local'};this.store.db.prepare("INSERT INTO system_storage_migrations VALUES(?,?,'verified',?,?,?)").run(id,JSON.stringify(scope),JSON.stringify(body),Date.now(),Date.now());});return this.list(scope).find(row=>row.id===id);
 }
 async transition(scope:ExpansionScope,id:string,action:'verify'|'cutover'|'rollback',authorize:()=>void){const job=this.row(scope,id);if(action==='verify'){if(String(job.state)!=='verified')throw new HttpError(409,'STORAGE_STATE','전환 전 검증 작업만 다시 확인할 수 있습니다.');const source=await this.operations.scopeData(scope),inventory=databaseInventory(source.db),shadow=new DatabaseSync(job.body.shadowFile,{readOnly:true});try{const copied=databaseInventory(shadow);const changed=Object.keys(inventory.hashes).filter(name=>name!=='runtime_state'&&inventory.hashes[name]!==copied.hashes[name]);return {verified:changed.length===0,changedTables:changed,counts:inventory.counts,requiresRecopy:changed.length>0};}finally{shadow.close();}}
 if(action==='cutover'&&String(job.state)==='active'||action==='rollback'&&String(job.state)==='rolled-back')return this.list(scope).find(row=>row.id===id);if(action==='cutover'&&String(job.state)!=='verified'||action==='rollback'&&String(job.state)!=='active')throw new HttpError(409,'STORAGE_STATE','현재 이전 단계에서 수행할 수 없는 작업입니다.');
 await this.operations.withScopeFreeze(scope,async source=>{authorize();const body=job.body;if(action==='cutover'){if(Number(this.store.db.prepare('SELECT config_version FROM expansion_environments WHERE id=?').get(scope.environmentId!)?.config_version)!==body.sourceConfigRevision)throw new HttpError(409,'CONFIG_CONFLICT','Environment configuration changed after storage review');const inventory=databaseInventory(source.db);if(JSON.stringify(inventory.hashes)!==JSON.stringify(body.hashes))throw new HttpError(409,'STORAGE_CHANGED','검증 이후 원본 데이터가 변경되었습니다. 다시 복사해 검토하세요.');transaction(this.store.db,()=>{this.store.operations.setState('storage:active:'+(scope.dataKey??scope.projectId),{file:body.shadowFile,migrationId:id});this.store.db.prepare("UPDATE system_storage_migrations SET state='active',updated_at=? WHERE id=?").run(Date.now(),id);});}else{const pointer=this.store.operations.state('storage:active:'+(scope.dataKey??scope.projectId));if(!pointer||record(pointer).migrationId!==id)throw new HttpError(409,'STORAGE_ACTIVE','다른 저장소가 현재 쓰기 대상으로 선택되어 있습니다.');const base=await realpath(this.dataRoot),parent=await realpath(path.dirname(body.originalFile)),original=path.join(parent,path.basename(body.originalFile));if(!contained(base,original))throw new HttpError(403,'STORAGE_PATH','Storage path is outside the managed directory');let originalExists=true;try{const checked=await realpath(original);if(checked!==original||!contained(base,checked))throw new HttpError(403,'STORAGE_PATH','Storage links are not supported');}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;originalExists=false;if(!body.reverseOriginalBackup||!contained(base,await realpath(body.reverseOriginalBackup)))throw new HttpError(409,'STORAGE_REVERSE_RECOVERY','The original storage is missing without a recoverable journal');}const temporary=original+'.reverse-'+randomUUID();source.snapshot(temporary);await inspectPortableDatabase(temporary,scope.projectId);const target=new DatabaseSync(temporary,{readOnly:true});try{if(JSON.stringify(databaseInventory(source.db))!==JSON.stringify(databaseInventory(target)))throw new HttpError(409,'STORAGE_REVERSE','Reverse copy differs from the current active data');}finally{target.close();}if(originalExists){body.reverseOriginalBackup=original+'.before-reverse-'+randomUUID();this.store.db.prepare('UPDATE system_storage_migrations SET body=?,updated_at=? WHERE id=?').run(JSON.stringify(body),Date.now(),id);await rename(original,body.reverseOriginalBackup);}await rename(temporary,original);transaction(this.store.db,()=>{this.store.operations.setState('storage:active:'+(scope.dataKey??scope.projectId),null);this.store.db.prepare("UPDATE system_storage_migrations SET state='rolled-back',updated_at=? WHERE id=?").run(Date.now(),id);});}});return this.list(scope).find(row=>row.id===id);
 }
}
