import type {IncomingMessage,ServerResponse} from 'node:http';
import {createHash,randomUUID} from 'node:crypto';
import type {Store} from './store';
import type {ExpansionService} from './expansion/service';
import type {OperationsService} from './operationsService';
import type {WorkQueue,WorkerPolicy} from './workQueue';
import type {AdvancementService} from './advancement/service';
import type {CreatorIdentity,ExpansionScope,ExpansionCapability} from '../src/domain/expansion';
import type {Experiment,ExperimentInput,RuntimeTask} from '../src/domain/systemRuntime';
import {body,HttpError,reply} from './http';
import {record} from '../src/domain/validation';
import {integer,text,transaction} from './platform/common';
import {runtimeIdentity,readiness} from './runtimeIdentity';
import {bindOperation} from './operationContext';
import {runtimeUseCase,SYSTEM_CONTRACT} from './useCases';
import {StorageMigrationService} from './storageMigration';
import {SystemObservability} from './systemObservability';
export class SystemRuntimeService {
 draining=false;
 readonly storage:StorageMigrationService;readonly observability:SystemObservability;
 constructor(readonly store:Store,readonly expansion:ExpansionService,readonly operations:OperationsService,readonly queue:WorkQueue,readonly advancement:AdvancementService,readonly root:string,readonly dataRoot:string){this.storage=new StorageMigrationService(store,operations,dataRoot);this.observability=new SystemObservability(store.db);}
 private scope(url:URL,input:Record<string,unknown>,creator:CreatorIdentity|null,local:boolean,cap:ExpansionCapability):ExpansionScope {
  for(const key of ['projectId','environmentId'])if(input[key]!==undefined&&url.searchParams.has(key)&&input[key]!==url.searchParams.get(key))throw new HttpError(403,'SCOPE_MISMATCH','본문과 조회 범위가 다릅니다.');
  const scope=this.expansion.access.resolve({projectId:typeof input.projectId==='string'?input.projectId:url.searchParams.get('projectId')??undefined,environmentId:typeof input.environmentId==='string'?input.environmentId:url.searchParams.get('environmentId')||undefined});return this.expansion.access.authorize(creator,scope,cap,local);
 }
 private experiments(scope:ExpansionScope):Experiment[]{this.store.db.prepare("UPDATE system_experiments SET status='stopped',stop_reason='duration-ended',stopped_at=? WHERE status='running' AND ends_at<=?").run(Date.now(),Date.now());return this.store.db.prepare('SELECT * FROM system_experiments WHERE project_id=? AND (environment_id IS ? OR environment_id=?) ORDER BY created_at DESC LIMIT 100').all(scope.projectId,scope.environmentId??null,scope.environmentId??null).map(row=>({...JSON.parse(String(row.body)) as ExperimentInput,id:String(row.id),scope,revision:Number(row.revision),status:String(row.status) as Experiment['status'],createdAt:Number(row.created_at),endsAt:Number(row.ends_at),stopReason:row.stop_reason?String(row.stop_reason):null}));}
 async handle(req:IncomingMessage,res:ServerResponse,url:URL,context:{creator:CreatorIdentity|null;localOwner:boolean}):Promise<boolean>{
  if(!url.pathname.startsWith('/api/advancement/runtime/'))return false;
  const input=req.method==='GET'?{}:record(await body(req,1000000)),route=url.pathname.slice('/api/advancement/runtime/'.length),contract=runtimeUseCase(route,req.method??'GET');if(!contract)throw new HttpError(404,'RUNTIME_ROUTE','등록된 운영 경로를 확인하세요.');const scope=this.scope(url,input,context.creator,context.localOwner,contract.capability);
  bindOperation(scope,context.creator?.id??'local-owner',context.creator?'creator':'local-owner');this.advancement.assertRequest(req,url,{...context,scope,input});
  const send=(data:unknown,status=200):true=>{reply(res,status,data);return true;};
  if(route==='contracts'&&req.method==='GET')return send(SYSTEM_CONTRACT);
  if(route==='observability'&&req.method==='GET')return send(this.observability.snapshot(scope));
  if(route==='alerts'&&req.method==='GET')return send(this.observability.policies(scope));
  const alert=route.match(/^alerts\/([a-zA-Z0-9_-]+)$/);if(alert&&req.method==='PUT'){this.advancement.platformAdministrator(context.creator,context.localOwner);return send(this.observability.configure(scope,alert[1]!,input));}
  if(route==='storage-migrations'&&req.method==='GET')return send(this.storage.list(scope));
  if(route==='storage-migrations'&&req.method==='POST'){this.advancement.platformAdministrator(context.creator,context.localOwner);return send(await this.storage.create(scope,input,()=>{this.expansion.access.authorize(context.creator,scope,'backup.restore',context.localOwner);this.advancement.platformAdministrator(context.creator,context.localOwner);}),201);}
  const migration=route.match(/^storage-migrations\/([a-zA-Z0-9_-]+)\/(verify|cutover|rollback)$/);if(migration&&req.method==='POST'){this.advancement.platformAdministrator(context.creator,context.localOwner);return send(await this.storage.transition(scope,migration[1]!,migration[2] as 'verify'|'cutover'|'rollback',()=>{this.expansion.access.authorize(context.creator,scope,'backup.restore',context.localOwner);this.advancement.platformAdministrator(context.creator,context.localOwner);}));}

  if(route==='operations'&&req.method==='GET'){const operations=this.store.db.prepare('SELECT operation_id AS id,request_id AS requestId,trace_id AS traceId,operation,status,base_revision AS baseRevision,request_key AS requestKey,started_at AS startedAt,finished_at AS finishedAt,error_code AS errorCode FROM system_operations WHERE organization_id=? AND project_id=? AND (? IS NULL OR environment_id=?) ORDER BY started_at DESC,operation_id DESC LIMIT 100').all(scope.organizationId,scope.projectId,scope.environmentId??null,scope.environmentId??null);return send(operations);}
  if(route==='collaboration'&&req.method==='GET'){
   const token=url.searchParams.get('after');let after=0,at=0;if(token){try{const value=JSON.parse(Buffer.from(token,'base64url').toString()) as unknown;if(!Array.isArray(value)||value.length!==4||!Number.isSafeInteger(value[0])||!Number.isSafeInteger(value[1])||value[2]!==scope.projectId||value[3]!==scope.environmentId||Number(value[0])<0||Number(value[1])<0)throw new Error('cursor');after=Number(value[0]);at=Number(value[1]);}catch{throw new HttpError(400,'COLLABORATION_CURSOR','Use the cursor issued for this environment');}}
   const resetRequired=Boolean(at&&at<Date.now()-30*86400000),events=this.store.db.prepare("SELECT rowid AS sequence,operation_id AS id,operation,status,started_at AS startedAt,finished_at AS finishedAt FROM system_operations WHERE organization_id=? AND project_id=? AND (? IS NULL OR environment_id=?) AND rowid>? AND operation NOT LIKE 'GET:%' AND operation NOT LIKE 'HEAD:%' ORDER BY rowid LIMIT 101").all(scope.organizationId,scope.projectId,scope.environmentId??null,scope.environmentId??null,resetRequired?0:after),project=this.store.project(scope.projectId);const shown=events.slice(0,100),last=shown.at(-1),cursor=last?Buffer.from(JSON.stringify([Number(last.sequence),Number(last.finishedAt),scope.projectId,scope.environmentId])).toString('base64url'):token??Buffer.from(JSON.stringify([0,Date.now(),scope.projectId,scope.environmentId])).toString('base64url');

   return send({events:shown,cursor,hasMore:events.length>100,resetRequired,comments:this.expansion.reviews.comments(scope).map(comment=>({...comment,targetStatus:comment.targetPath==='project'||comment.targetPath.startsWith('blocks.')&&project?.blocks.some(block=>comment.targetPath.startsWith('blocks.'+block.id+'.'))?'active':'missing'})),reviews:this.expansion.reviews.list(scope),presence:this.expansion.reviews.presence(scope),projectRevision:project?.revision});
  }
  if(route==='overview'&&req.method==='GET'){
   const tasks:RuntimeTask[]=[],project=this.store.project(scope.projectId);if(!project)throw new HttpError(404,'PROJECT_NOT_FOUND','프로젝트가 없습니다.');
   const work=this.store.db.prepare("SELECT id,kind,status,error_code FROM work_items WHERE organization_id=? AND json_extract(scope,'$.projectId')=? AND (? IS NULL OR json_extract(scope,'$.environmentId')=?) AND status IN('waiting','running','unknown','failed') ORDER BY created_at DESC LIMIT 50").all(scope.organizationId,scope.projectId,scope.environmentId??null,scope.environmentId??null);
   for(const item of work)tasks.push({id:String(item.id),kind:'job.'+String(item.kind),title:String(item.kind)+' 작업',status:String(item.status),projectId:scope.projectId,environmentId:scope.environmentId,nextAction:item.status==='unknown'?'공급자 상태를 대사하고 근거를 확인하세요.':item.status==='failed'?'오류 원인을 확인한 뒤 다시 실행하세요.':'현재 실행 상태를 확인하세요.',...(item.error_code?{reason:String(item.error_code)}:{})});
   if(this.expansion.access.capabilities(context.creator,scope,context.localOwner).includes('review.approve'))for(const item of this.store.db.prepare("SELECT id,revision FROM expansion_reviews WHERE project_id=? AND status='pending' ORDER BY created_at LIMIT 30").all(scope.projectId))tasks.push({id:String(item.id),kind:'review.pending',title:`원본 ${item.revision} 검토`,status:'pending',projectId:scope.projectId,nextAction:'해당 원본과 변경 내역을 검토하세요.'});
   for(const activation of this.store.db.prepare("SELECT id FROM system_release_activations WHERE project_id=? AND target_environment_id IS ? AND status='unknown' LIMIT 30").all(scope.projectId,scope.environmentId??null))tasks.push({id:String(activation.id),kind:'release.unknown',title:'Interrupted promotion',status:'unknown',projectId:scope.projectId,environmentId:scope.environmentId,nextAction:'Reconcile activation and immutable artifact before retry'});
   if(!this.store.db.prepare("SELECT id FROM exports WHERE project_id=? AND status='ready' LIMIT 1").get(scope.projectId))tasks.push({id:'first-publish',kind:'onboarding.publish',title:'첫 사이트 결과 만들기',status:'pending',projectId:scope.projectId,nextAction:'품질 검사를 확인하고 선택한 환경에 사이트를 생성하세요.'});
   const ready=readiness(this.root,this.dataRoot,this.store,this.draining);return send({runtime:{...runtimeIdentity(this.root,this.store,this.expansion.mode),ready:ready.ready},readiness:ready,tasks,operations:work,metrics:this.queue.metrics(scope.organizationId,scope.projectId,scope.environmentId),flags:this.advancement.config.flags(scope)});
  }
  if(route==='worker-policy'&&req.method==='GET'){this.advancement.platformAdministrator(context.creator,context.localOwner);this.expansion.access.authorize(context.creator,scope,'team.manage',context.localOwner);return send({revision:Number(this.store.db.prepare("SELECT revision FROM system_worker_policy WHERE id='global'").get()?.revision),policy:this.queue.policy()});}
  if(route==='worker-policy'&&req.method==='PUT'){this.advancement.platformAdministrator(context.creator,context.localOwner);this.expansion.access.authorize(context.creator,scope,'team.manage',context.localOwner);const value=record(input.policy),pools=record(value.pools);const policy:WorkerPolicy={maxRunning:integer(value.maxRunning,'동시 실행',1,16),pools:{standard:integer(pools.standard,'일반 작업',1,16),cpu:integer(pools.cpu,'CPU 작업',1,16),io:integer(pools.io,'외부 작업',1,16),recovery:integer(pools.recovery,'복구 작업',1,16)},maxDurationMs:integer(value.maxDurationMs,'시간 예산',1000,3600000),drainMs:integer(value.drainMs,'종료 예산',100,30000)};return send(this.queue.configurePolicy(policy,integer(input.baseRevision,'설정 버전',1)));}
  if(route==='experiments'&&req.method==='GET')return send(this.experiments(scope));
  const reconcile=route.match(/^releases\/([a-zA-Z0-9_-]+)\/reconcile$/);if(reconcile&&req.method==='POST')return send(await this.operations.reconcilePromotion(reconcile[1]!,scope,()=>this.expansion.access.authorize(context.creator,scope,'project.publish',context.localOwner)));
  const promotion=route.match(/^releases\/([a-zA-Z0-9_-]+)\/(preview|promote)$/);
  if(promotion){const targetId=typeof input.targetEnvironmentId==='string'?input.targetEnvironmentId:url.searchParams.get('targetEnvironmentId');if(!targetId)throw new HttpError(400,'RELEASE_TARGET','대상 환경을 선택하세요.');const target=this.expansion.access.environment(targetId);this.expansion.access.authorize(context.creator,target,'project.publish',context.localOwner);this.expansion.access.authorize(context.creator,scope,'project.publish',context.localOwner);if(promotion[2]==='preview'&&req.method==='GET')return send(await this.operations.releasePreview(promotion[1]!,scope,target));if(promotion[2]==='promote'&&req.method==='POST')return send(await this.operations.promoteRelease(promotion[1]!,scope,target,integer(input.expectedConfigRevision,'대상 설정 버전',1),text(input.requestKey,'승격 요청 키',100),(artifactProject)=>{this.expansion.access.authorize(context.creator,target,'project.publish',context.localOwner);this.expansion.access.authorize(context.creator,scope,'project.publish',context.localOwner);this.advancement.assertJob(target,'site.promote');this.expansion.assertPublication(target,artifactProject??this.store.project(target.projectId)??undefined);},text(input.reviewFingerprint,'Review fingerprint',64)));}
  if(route==='experiments'&&req.method==='POST'){
   const unit=input.unit,metric=input.metric;if(unit!=='account'&&unit!=='workspace'||!['first-publish','save-success','task-completed'].includes(String(metric))||!Array.isArray(input.variants)||input.variants.length<2||input.variants.length>5||typeof input.guardrailErrorRate!=='number'||input.guardrailErrorRate<0||input.guardrailErrorRate>1)throw new HttpError(400,'EXPERIMENT_INPUT','할당 단위·목표 지표·안전 한도를 확인하세요.');
   const variants=input.variants.map(value=>{const v=record(value),id=text(v.id,'변형 ID',80);if(!/^[a-zA-Z0-9_-]+$/.test(id))throw new HttpError(400,'EXPERIMENT_VARIANT','변형 ID를 확인하세요.');return {id,name:text(v.name,'변형 이름',100)};});if(new Set(variants.map(v=>v.id)).size!==variants.length)throw new HttpError(400,'EXPERIMENT_VARIANT','변형 ID가 중복됩니다.');
   const value:ExperimentInput={name:text(input.name,'실험 이름',120),hypothesis:text(input.hypothesis,'가설',2000),unit,metric:metric as ExperimentInput['metric'],minSamples:integer(input.minSamples,'최소 표본',10,1000000),guardrailErrorRate:input.guardrailErrorRate,variants,durationDays:integer(input.durationDays,'실험 기간',1,90)},id=randomUUID(),now=Date.now();this.store.db.prepare("INSERT INTO system_experiments VALUES(?,?,?,?,?,1,?,'running',?,?,NULL,NULL)").run(id,scope.organizationId,scope.workspaceId,scope.projectId,scope.environmentId??null,JSON.stringify(value),now,now+value.durationDays*86400000);return send(this.experiments(scope).find(item=>item.id===id),201);
  }
  const action=route.match(/^experiments\/([a-zA-Z0-9_-]+)\/(assignment|events|stop|report)$/);
  if(action){const experiment=this.experiments(scope).find(item=>item.id===action[1]);if(!experiment)throw new HttpError(404,'EXPERIMENT_NOT_FOUND','선택한 범위의 실험이 없습니다.');
   const unit=experiment.unit==='workspace'?scope.workspaceId:context.creator?.id??(context.localOwner?'local-owner':null);if(!unit||input.unitId!==undefined&&input.unitId!==unit)throw new HttpError(403,'EXPERIMENT_UNIT','현재 계정 또는 작업공간만 할당할 수 있습니다.');const unitHash=createHash('sha256').update(experiment.id+'\0'+unit).digest('hex');
   if(action[2]==='assignment'&&req.method==='POST'){if(experiment.status!=='running')throw new HttpError(409,'EXPERIMENT_STOPPED','종료된 실험입니다.');const existing=this.store.db.prepare('SELECT * FROM system_experiment_assignments WHERE experiment_id=? AND unit_hash=?').get(experiment.id,unitHash);if(existing)return send({id:String(existing.id),assignmentId:String(existing.id),variant:String(existing.variant)});const id=randomUUID(),variant=experiment.variants[parseInt(unitHash.slice(0,8),16)%experiment.variants.length]!.id;this.store.db.prepare('INSERT INTO system_experiment_assignments VALUES(?,?,?,?,?)').run(id,experiment.id,unitHash,variant,Date.now());return send({id,assignmentId:id,variant});}
   if(action[2]==='events'&&req.method==='POST'){if(experiment.status!=='running')throw new HttpError(409,'EXPERIMENT_STOPPED','종료된 실험입니다.');const assignment=this.store.db.prepare('SELECT * FROM system_experiment_assignments WHERE id=? AND experiment_id=? AND unit_hash=?').get(text(input.assignmentId,'할당 ID',100),experiment.id,unitHash);if(!assignment)throw new HttpError(403,'EXPERIMENT_ASSIGNMENT','현재 사용자의 할당이 아닙니다.');if(input.metric!==experiment.metric)throw new HttpError(400,'EXPERIMENT_METRIC','지정한 목표 지표를 사용하세요.');const id=text(input.eventId,'이벤트 ID',100),value=integer(input.value??1,'측정 값',0,1000000),failed=input.failed===true?1:0;transaction(this.store.db,()=>{const previous=this.store.db.prepare('SELECT * FROM system_experiment_events WHERE id=?').get(id);if(previous){if(previous.experiment_id!==experiment.id||previous.assignment_id!==assignment.id||previous.metric!==input.metric||Number(previous.value)!==value||Number(previous.failed)!==failed)throw new HttpError(409,'EXPERIMENT_EVENT','같은 이벤트 ID의 내용이 다릅니다.');return;}this.store.db.prepare('INSERT INTO system_experiment_events VALUES(?,?,?,?,?,?,?)').run(id,experiment.id,String(assignment.id),experiment.metric,value,failed,Date.now());});const totals=this.store.db.prepare('SELECT COUNT(*) AS n,SUM(failed) AS failures FROM system_experiment_events WHERE experiment_id=?').get(experiment.id)!;if(Number(totals.n)>=10&&Number(totals.failures)/Number(totals.n)>experiment.guardrailErrorRate)this.store.db.prepare("UPDATE system_experiments SET status='stopped',stop_reason='guardrail-error-rate',stopped_at=?,revision=revision+1 WHERE id=?").run(Date.now(),experiment.id);return send({ack:true,eventId:id});}
   if(action[2]==='stop'&&req.method==='POST'){this.store.db.prepare("UPDATE system_experiments SET status='stopped',stop_reason=?,stopped_at=?,revision=revision+1 WHERE id=? AND status='running'").run(text(input.reason,'종료 사유',1000),Date.now(),experiment.id);return send(this.experiments(scope).find(item=>item.id===experiment.id));}
   if(action[2]==='report'&&req.method==='GET'){const rows=this.store.db.prepare('SELECT a.variant,COUNT(DISTINCT a.id) AS assigned,COUNT(e.id) AS samples,COALESCE(SUM(e.value),0) AS value,COALESCE(SUM(e.failed),0) AS failures FROM system_experiment_assignments a LEFT JOIN system_experiment_events e ON e.assignment_id=a.id WHERE a.experiment_id=? GROUP BY a.variant').all(experiment.id);return send({experiment,variants:rows,sufficient:rows.length===experiment.variants.length&&rows.every(row=>Number(row.samples)>=experiment.minSamples),decision:'manual-review-required'});}
  }
  throw new HttpError(404,'RUNTIME_ROUTE','운영 기능 경로를 확인하세요.');
 }
}
