import type {DatabaseSync} from 'node:sqlite';
import {randomUUID} from 'node:crypto';
import type {ExpansionScope} from '../src/domain/expansion';
import {HttpError} from './http';
import {integer,transaction} from './platform/common';
import {scopeKey} from './advancement/common';
import {record} from '../src/domain/validation';
export class SystemObservability {
 constructor(readonly db:DatabaseSync){}
 snapshot(scope:ExpansionScope){const spans=this.db.prepare('SELECT id,trace_id AS traceId,parent_id AS parentId,operation,started_at AS startedAt,duration_ms AS durationMs,status,error_code AS errorCode FROM system_trace_spans WHERE organization_id=? AND project_id=? AND (? IS NULL OR environment_id=?) ORDER BY started_at DESC LIMIT 100').all(scope.organizationId,scope.projectId,scope.environmentId??null,scope.environmentId??null);const metrics=this.db.prepare('SELECT operation,status,COUNT(*) AS requests,ROUND(AVG(duration_ms)) AS averageMs,MAX(duration_ms) AS maxMs FROM system_trace_spans WHERE organization_id=? AND project_id=? AND (? IS NULL OR environment_id=?) AND started_at>? GROUP BY operation,status LIMIT 100').all(scope.organizationId,scope.projectId,scope.environmentId??null,scope.environmentId??null,Date.now()-3600000);this.evaluate(scope);return {spans,metrics,incidents:this.db.prepare('SELECT id,kind,status,body,created_at AS createdAt,updated_at AS updatedAt FROM system_incidents WHERE organization_id=? AND project_id=? AND (? IS NULL OR environment_id=?) ORDER BY updated_at DESC LIMIT 50').all(scope.organizationId,scope.projectId,scope.environmentId??null,scope.environmentId??null).map(row=>({...row,body:JSON.parse(String(row.body)) as unknown})),exporter:{protocol:'otlp-http-json',status:process.env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT?'configured':'not-configured'}};}
 policies(scope:ExpansionScope){return this.db.prepare('SELECT id,metric,threshold,window_ms AS windowMs,revision,enabled FROM system_alert_policies WHERE scope_key=? ORDER BY id LIMIT 100').all(scopeKey(scope));}
 configure(scope:ExpansionScope,id:string,input:Record<string,unknown>){if(!/^[a-zA-Z0-9_-]{1,80}$/.test(id)||!['http-errors','queue-unknown','outbox-blocked','latency-ms'].includes(String(input.metric))||typeof input.enabled!=='boolean')throw new HttpError(400,'ALERT_INPUT','지원하는 알림 지표와 활성 상태를 지정하세요.');const base=integer(input.baseRevision,'알림 버전',0),threshold=integer(input.threshold,'알림 기준',0,1000000),windowMs=integer(input.windowMs,'측정 구간',1000,86400000);transaction(this.db,()=>{const current=this.db.prepare('SELECT revision FROM system_alert_policies WHERE scope_key=? AND id=?').get(scopeKey(scope),id);if(Number(current?.revision??0)!==base)throw new HttpError(409,'ALERT_CONFLICT','알림 설정이 변경되었습니다.');this.db.prepare('INSERT INTO system_alert_policies VALUES(?,?,?,?,?,?,?) ON CONFLICT(scope_key,id) DO UPDATE SET metric=excluded.metric,threshold=excluded.threshold,window_ms=excluded.window_ms,revision=excluded.revision,enabled=excluded.enabled').run(scopeKey(scope),id,String(input.metric),threshold,windowMs,base+1,input.enabled?1:0);});return this.policies(scope).find(row=>row.id===id);}
 evaluate(scope:ExpansionScope):void {for(const policy of this.policies(scope)){const from=Date.now()-Number(policy.windowMs);let value:number;if(policy.metric==='http-errors'||policy.metric==='latency-ms'){const row=this.db.prepare("SELECT COUNT(*) AS errors,COALESCE(MAX(duration_ms),0) AS latency FROM system_trace_spans WHERE organization_id=? AND project_id=? AND (? IS NULL OR environment_id=?) AND started_at>? AND (?='latency-ms' OR status='error')").get(scope.organizationId,scope.projectId,scope.environmentId??null,scope.environmentId??null,from,String(policy.metric));value=Number(policy.metric==='http-errors'?row?.errors:row?.latency);}else if(policy.metric==='queue-unknown')value=Number(this.db.prepare("SELECT COUNT(*) AS n FROM work_items WHERE organization_id=? AND json_extract(scope,'$.projectId')=? AND (? IS NULL OR json_extract(scope,'$.environmentId')=?) AND status='unknown'").get(scope.organizationId,scope.projectId,scope.environmentId??null,scope.environmentId??null)?.n);else value=Number(this.db.prepare("SELECT COUNT(*) AS n FROM system_event_outbox WHERE organization_id=? AND project_id=? AND (? IS NULL OR environment_id=?) AND status IN('failed','blocked')").get(scope.organizationId,scope.projectId,scope.environmentId??null,scope.environmentId??null)?.n);const kind='alert:'+String(policy.id),active=this.db.prepare("SELECT id FROM system_incidents WHERE organization_id=? AND project_id=? AND environment_id IS ? AND kind=? AND status='open'").get(scope.organizationId,scope.projectId,scope.environmentId??null,kind);if(Boolean(policy.enabled)&&value>Number(policy.threshold)){const body=JSON.stringify({metric:policy.metric,value,threshold:policy.threshold,policyRevision:policy.revision});if(active)this.db.prepare('UPDATE system_incidents SET body=?,updated_at=? WHERE id=?').run(body,Date.now(),String(active.id));else this.db.prepare("INSERT INTO system_incidents VALUES(?,?,?,?,?,'open',?,?,?)").run(randomUUID(),scope.organizationId,scope.projectId,scope.environmentId??null,kind,body,Date.now(),Date.now());}else if(active)this.db.prepare("UPDATE system_incidents SET status='resolved',updated_at=? WHERE id=?").run(Date.now(),String(active.id));}}
}
// IDs stay in trace records, never in metric labels; payloads and tenant attributes are excluded.
export function otlpSpans(rows:Record<string,unknown>[]):unknown{return {resourceSpans:[{resource:{attributes:[{key:'service.name',value:{stringValue:'automade-studio'}}]},scopeSpans:[{scope:{name:'automade.operations',version:'1'},spans:rows.map(row=>({traceId:String(row.trace_id),spanId:String(row.id).replaceAll('-','').slice(0,16),...(row.parent_id?{parentSpanId:String(row.parent_id).replaceAll('-','').slice(0,16)}:{}),name:String(row.operation),kind:1,startTimeUnixNano:String(BigInt(Number(row.started_at))*1000000n),endTimeUnixNano:String(BigInt(Number(row.started_at)+Number(row.duration_ms))*1000000n),status:{code:row.status==='error'?2:1},attributes:row.error_code?[{key:'error.type',value:{stringValue:String(row.error_code)}}]:[]}))}]}]};}
export async function exportOtlp(db:DatabaseSync,endpoint=process.env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT):Promise<{status:string;exported:number}>{if(!endpoint)return {status:'not-configured',exported:0};const target=new URL(endpoint);if(target.username||target.password||target.hash||target.search||target.protocol!=='https:'&&!(target.protocol==='http:'&&['127.0.0.1','localhost','[::1]'].includes(target.hostname)))throw new HttpError(400,'OTLP_ENDPOINT','HTTPS 수집기 또는 로컬 수집기 주소를 지정하세요.');const cursor=record(JSON.parse(String(db.prepare("SELECT value FROM runtime_state WHERE key='telemetry:export-cursor'").get()?.value??'{}'))),sequence=Number(cursor.sequence??0),present=sequence===0||Boolean(db.prepare('SELECT id FROM system_trace_spans WHERE rowid=? AND id=?').get(sequence,String(cursor.id??''))),rows=db.prepare('SELECT rowid AS sequence,* FROM system_trace_spans WHERE rowid>? ORDER BY rowid LIMIT 200').all(present?sequence:0);if(!rows.length)return {status:'idle',exported:0};const response=await fetch(target,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(otlpSpans(rows)),signal:AbortSignal.timeout(5000),redirect:'error'});if(!response.ok)throw new HttpError(503,'OTLP_EXPORT','수집기가 추적 데이터를 수락하지 않았습니다.');const result=record(await response.json());if(result.partialSuccess&&Number(record(result.partialSuccess).rejectedSpans)>0)throw new HttpError(503,'OTLP_PARTIAL','수집기가 일부 추적 데이터를 거부했습니다.');const last=rows.at(-1)!;db.prepare("INSERT INTO runtime_state VALUES('telemetry:export-cursor',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(JSON.stringify({sequence:Number(last.sequence),id:String(last.id)}));return {status:'exported',exported:rows.length};}
