import { randomUUID } from "node:crypto";
import type { DatabaseSync } from "node:sqlite";
import { HttpError } from "../http";
import { audit, boolean, consumeUsage, hash, integer, many, now, one, text, transaction, type SqlRow } from "../platform/common";
import { recordPlatformEvent } from "../platform/events";
import { assertFinancialReady } from "./reconciliation";
import type { BookingRecurrence, OrderFulfillment } from "../../src/domain/expansion";
import type { BookingChangeReview } from "../../src/domain/advancement";
import { resolveWallTime } from "../../src/domain/timezones";
import { fingerprint } from "../advancement/common";
import { record } from "../../src/domain/validation";
import { saveResource } from "../platform/business";
const date = (value: unknown): string => { const result = text(value, "현지 날짜", 10); if (!/^\d{4}-\d{2}-\d{2}$/.test(result) || !Number.isFinite(Date.parse(result + "T00:00:00Z")) || new Date(result + "T00:00:00Z").toISOString().slice(0, 10) !== result) throw new HttpError(400, "BOOKING_DATE", "현지 날짜를 확인하세요."); return result; };
function ruleValues(input:Record<string,unknown>,resource:SqlRow){
  const startDate=date(input.startDate),endDate=date(input.endDate),weekdays=input.weekdays,startTime=text(input.startTime,'현지 시각',5),name=text(input.name,'반복 규칙 이름',100),duration=integer(input.durationMinutes,'예약 분',5,1440),capacity=integer(input.capacity??resource.capacity,'정원',1,Number(resource.capacity)),enabled=boolean(input.enabled,'활성화',true),zone=text(input.timeZone??'UTC','IANA 시간대',100),disambiguation=input.disambiguation??'reject',gapPolicy=input.gapPolicy??'reject';
  if(endDate<startDate||Date.parse(endDate)-Date.parse(startDate)>180*86400_000||!/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(startTime)||!Array.isArray(weekdays)||!weekdays.length||weekdays.length>7||weekdays.some(day=>!Number.isInteger(day)||day<0||day>6))throw new HttpError(400,'BOOKING_RULE','반복 요일·기간(180일 이내)·현지 시간을 확인하세요.');
  if(!['reject','earlier','later'].includes(String(disambiguation))||!['reject','shift-forward'].includes(String(gapPolicy)))throw new HttpError(400,'BOOKING_TIME_ZONE','시간 중복·공백 선택을 확인하세요.');
  try{new Intl.DateTimeFormat('en',{timeZone:zone}).resolvedOptions();}catch{throw new HttpError(400,'BOOKING_TIME_ZONE','올바른 IANA 시간대를 선택하세요.');}
  const days=[...new Set(weekdays)] as number[];
  for(let clock=Date.parse(startDate+'T00:00:00Z');clock<=Date.parse(endDate+'T00:00:00Z');clock+=86400_000){const day=new Date(clock);if(days.includes(day.getUTCDay()))resolveWallTime({date:day.toISOString().slice(0,10),time:startTime,timeZone:zone,disambiguation:disambiguation as 'reject'|'earlier'|'later',gapPolicy:gapPolicy as 'reject'|'shift-forward'});}
  return {startDate,endDate,weekdays:days,startTime,name,duration,capacity,enabled,zone,disambiguation:String(disambiguation),gapPolicy:String(gapPolicy)};
}
export function holiday(db: DatabaseSync, projectId: string, resourceId: string, startsAt: string): boolean {const provenance=one(db,'SELECT wall_time FROM advancement_booking_slot_provenance p JOIN platform_slots s ON s.id=p.slot_id WHERE s.resource_id=? AND s.starts_at=?',resourceId,startsAt);return Boolean(one(db, "SELECT 1 FROM expansion_booking_holidays WHERE project_id=? AND resource_id=? AND date=?", projectId, resourceId, provenance?String(provenance.wall_time).slice(0,10):startsAt.slice(0, 10))); }
export function offered(db: DatabaseSync, slotId: string): number { return Number(one(db, "SELECT COALESCE(SUM(quantity),0) AS total FROM expansion_booking_waitlist WHERE slot_id=? AND status='offered' AND offer_expires_at>?", slotId, Date.now())?.total ?? 0); }
export class BookingExpansion {
  constructor(readonly db: DatabaseSync) {}
  rules(projectId: string): BookingRecurrence[] { return many(this.db, "SELECT r.*,z.time_zone,z.disambiguation,z.gap_policy,z.revision FROM expansion_booking_rules r LEFT JOIN advancement_booking_zones z ON z.rule_id=r.id WHERE r.project_id=? ORDER BY r.created_at DESC LIMIT 100", projectId).map(row => ({ id: String(row.id), projectId: String(row.project_id), resourceId: String(row.resource_id), name: String(row.name), startDate: String(row.start_date), endDate: String(row.end_date), weekdays: JSON.parse(String(row.weekdays)) as number[], startTime: String(row.start_time), durationMinutes: Number(row.duration_minutes), capacity: Number(row.capacity), enabled: Boolean(row.enabled), createdAt: String(row.created_at),timeZone:String(row.time_zone??'UTC'),disambiguation:String(row.disambiguation??'reject') as BookingRecurrence['disambiguation'],gapPolicy:String(row.gap_policy??'reject') as BookingRecurrence['gapPolicy'],revision:Number(row.revision??1) })); }
  holidays(projectId: string): SqlRow[] { return many(this.db, "SELECT resource_id AS resourceId,date,reason FROM expansion_booking_holidays WHERE project_id=? ORDER BY date LIMIT 500", projectId); }
  saveHoliday(projectId: string, input: Record<string, unknown>, remove = false,reviewed=false): void {
    const resourceId = text(input.resourceId, "자원 ID", 100), day = date(input.date);
    if (!one(this.db, "SELECT 1 FROM platform_resources WHERE id=? AND project_id=?", resourceId, projectId)) throw new HttpError(404, "RESOURCE", "예약 자원을 찾을 수 없습니다.");
    if (!remove && one(this.db, "SELECT 1 FROM platform_bookings b JOIN platform_slots s ON s.id=b.slot_id LEFT JOIN advancement_booking_slot_provenance p ON p.slot_id=s.id WHERE b.status='confirmed' AND s.resource_id=? AND substr(COALESCE(p.wall_time,s.starts_at),1,10)=?", resourceId, day)) throw new HttpError(409, "HOLIDAY_BOOKED", "확정 예약이 있는 날짜입니다. 먼저 예약을 처리하세요.");
    if(!remove&&!reviewed&&many(this.db,"SELECT s.starts_at,p.wall_time FROM platform_slots s LEFT JOIN advancement_booking_slot_provenance p ON p.slot_id=s.id WHERE s.resource_id=? AND s.starts_at>?",resourceId,now()).some(slot=>String(slot.wall_time??slot.starts_at).slice(0,10)===day))throw new HttpError(409,'BOOKING_REVIEW_REQUIRED','기존 생성 일정에 적용할 휴일은 예약·대기 영향 검토를 먼저 완료하세요.');
    if (remove) this.db.prepare("DELETE FROM expansion_booking_holidays WHERE project_id=? AND resource_id=? AND date=?").run(projectId, resourceId, day); else this.db.prepare("INSERT INTO expansion_booking_holidays VALUES(?,?,?,?) ON CONFLICT DO UPDATE SET reason=excluded.reason").run(projectId, resourceId, day, text(input.reason ?? "", "휴일 사유", 1000, true)); audit(this.db, "booking.holiday", resourceId);
  }
  saveRule(projectId: string, input: Record<string, unknown>, id?: string,reviewed=false): BookingRecurrence {
    const resourceId = text(input.resourceId, "자원 ID", 100), resource = one(this.db, "SELECT * FROM platform_resources WHERE id=? AND project_id=? AND active=1", resourceId, projectId); if (!resource) throw new HttpError(404, "RESOURCE", "활성 예약 자원을 찾을 수 없습니다.");
    const values=ruleValues(input,resource);
    const key = id ?? randomUUID(); if (id && !one(this.db, "SELECT 1 FROM expansion_booking_rules WHERE id=? AND project_id=?", id, projectId)) throw new HttpError(404, "BOOKING_RULE", "반복 규칙을 찾을 수 없습니다.");
    if(id&&!reviewed&&one(this.db,'SELECT 1 FROM platform_slots WHERE resource_id=? AND starts_at>?',resourceId,now()))throw new HttpError(409,'BOOKING_REVIEW_REQUIRED','이미 생성된 일정은 보존됩니다. 반복 규칙 변경의 예약·대기 영향을 먼저 검토하세요.');
    if(id&&one(this.db,'SELECT resource_id FROM expansion_booking_rules WHERE id=?',id)?.resource_id!==resourceId)throw new HttpError(409,'BOOKING_RULE_RESOURCE','반복 규칙의 자원 변경은 새 규칙으로 분리하세요.');
    const write=()=>{this.db.prepare("INSERT INTO expansion_booking_rules VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,start_date=excluded.start_date,end_date=excluded.end_date,weekdays=excluded.weekdays,start_time=excluded.start_time,duration_minutes=excluded.duration_minutes,capacity=excluded.capacity,enabled=excluded.enabled").run(key, projectId, resourceId, values.name, values.startDate, values.endDate, JSON.stringify(values.weekdays), values.startTime, values.duration, values.capacity, values.enabled ? 1 : 0, now());this.db.prepare("INSERT INTO advancement_booking_zones VALUES(?,?,?,?,1) ON CONFLICT(rule_id) DO UPDATE SET time_zone=excluded.time_zone,disambiguation=excluded.disambiguation,gap_policy=excluded.gap_policy,revision=revision+1").run(key,values.zone,values.disambiguation,values.gapPolicy);};if(reviewed)write();else transaction(this.db,write);return this.rules(projectId).find(row => row.id === key)!;
  }
  private reviewSnapshot(projectId:string,kind:string,targetId:string,input:Record<string,unknown>):{resource:SqlRow;rule:SqlRow|null;slots:SqlRow[];holidays:SqlRow[]} {
    const rule=kind==='rule'?one(this.db,'SELECT r.*,z.time_zone,z.disambiguation,z.gap_policy,z.revision FROM expansion_booking_rules r LEFT JOIN advancement_booking_zones z ON z.rule_id=r.id WHERE r.id=? AND r.project_id=?',targetId,projectId):null;
    if(kind==='rule'&&!rule)throw new HttpError(404,'BOOKING_RULE','이 프로젝트의 반복 규칙을 찾을 수 없습니다.');
    const resourceId=rule?String(rule.resource_id):targetId,resource=one(this.db,'SELECT * FROM platform_resources WHERE id=? AND project_id=?',resourceId,projectId);if(!resource)throw new HttpError(404,'RESOURCE','이 프로젝트의 예약 자원을 찾을 수 없습니다.');
    const slots=many(this.db,"SELECT s.*,p.wall_time,(SELECT COALESCE(SUM(b.quantity),0) FROM platform_bookings b WHERE b.slot_id=s.id AND b.status='confirmed') AS reserved,(SELECT COALESCE(SUM(w.quantity),0) FROM expansion_booking_waitlist w WHERE w.slot_id=s.id AND w.status='offered' AND w.offer_expires_at>?) AS offered,(SELECT COUNT(*) FROM expansion_booking_waitlist w WHERE w.slot_id=s.id AND w.status='waiting') AS waiting,(SELECT COALESCE(MAX(w.quantity),0) FROM expansion_booking_waitlist w WHERE w.slot_id=s.id AND w.status='waiting') AS waitingQuantity FROM platform_slots s LEFT JOIN advancement_booking_slot_provenance p ON p.slot_id=s.id WHERE s.resource_id=? AND s.starts_at>? ORDER BY s.id LIMIT 2001",Date.now(),resourceId,now());if(slots.length>2000)throw new HttpError(409,'BOOKING_REVIEW_LIMIT','예약 일정이 많습니다. 자원을 나누어 검토하세요.');
    return {resource,rule,slots:kind==='holiday'?slots.filter(slot=>String(slot.wall_time??slot.starts_at).slice(0,10)===date(input.date)):slots,holidays:many(this.db,'SELECT * FROM expansion_booking_holidays WHERE project_id=? AND resource_id=? ORDER BY date',projectId,resourceId)};
  }
  private reviewDto(row:SqlRow):BookingChangeReview {const body=record(JSON.parse(String(row.body)));return {id:String(row.id),approvalFingerprint:String(row.approval_fingerprint),affected:record(body.affected) as BookingChangeReview['affected'],conflicts:body.conflicts as string[],expiresAt:new Date(Number(row.expires_at)).toISOString(),preservesMaterializedSlots:true,...(row.applied_at?{applied:true}:{})};}
  previewChange(projectId:string,input:Record<string,unknown>):BookingChangeReview {
    const kind=String(input.kind),targetId=text(input.targetId,'검토 대상',100),proposed=record(input.input);if(!['resource','rule','holiday'].includes(kind))throw new HttpError(400,'BOOKING_REVIEW_KIND','자원·반복 규칙·휴일 변경을 선택하세요.');const snapshot=this.reviewSnapshot(projectId,kind,targetId,proposed),affected={slots:snapshot.slots.length,confirmed:snapshot.slots.reduce((sum,slot)=>sum+Number(slot.reserved),0),offered:snapshot.slots.reduce((sum,slot)=>sum+Number(slot.offered),0),waiting:snapshot.slots.reduce((sum,slot)=>sum+Number(slot.waiting),0)},conflicts:string[]=[];
    if(kind==='resource'){const capacity=integer(proposed.capacity,'변경 정원',1,10000),active=boolean(proposed.active,'사용 상태',true);if(snapshot.slots.some(slot=>Number(slot.reserved)+Number(slot.offered)>capacity))conflicts.push('CONFIRMED_OR_OFFERED_CAPACITY');if(snapshot.slots.some(slot=>Number(slot.waitingQuantity)>capacity))conflicts.push('WAITLIST_QUANTITY');if(!active&&(affected.confirmed||affected.offered||affected.waiting))conflicts.push('ACTIVE_RESERVATIONS');text(proposed.name,'자원 이름',100);}
    if(kind==='holiday'){date(proposed.date);if(proposed.remove!==true){if(affected.confirmed||affected.offered)conflicts.push('HOLIDAY_RESERVATIONS');if(affected.waiting)conflicts.push('HOLIDAY_WAITLIST');}}
    if(kind==='rule'){ruleValues(proposed,snapshot.resource);if(proposed.resourceId!==snapshot.resource.id)throw new HttpError(409,'BOOKING_RULE_RESOURCE','반복 규칙의 자원 변경은 새 규칙으로 분리하세요.');}
    const id=randomUUID(),base=fingerprint(snapshot),approval=fingerprint([projectId,kind,targetId,base,proposed]),expires=Date.now()+900000;
    this.db.prepare('INSERT INTO advancement_booking_reviews VALUES(?,?,?,?,?,?,?,?,NULL)').run(id,projectId,kind,targetId,base,approval,JSON.stringify({input:proposed,affected,conflicts}),expires);return {id,approvalFingerprint:approval,affected,conflicts,expiresAt:new Date(expires).toISOString(),preservesMaterializedSlots:true};
  }
  applyChange(projectId:string,id:string,approval:unknown):BookingChangeReview {return transaction(this.db,()=>{const row=one(this.db,'SELECT * FROM advancement_booking_reviews WHERE id=? AND project_id=?',id,projectId);if(!row||row.approval_fingerprint!==approval||Number(row.expires_at)<=Date.now())throw new HttpError(409,'BOOKING_REVIEW_EXPIRED','같은 예약 변경의 유효한 검토가 필요합니다.');if(row.applied_at)return this.reviewDto(row);const body=record(JSON.parse(String(row.body))),input=record(body.input),kind=String(row.kind),snapshot=this.reviewSnapshot(projectId,kind,String(row.target_id),input);if(fingerprint(snapshot)!==row.base_fingerprint)throw new HttpError(409,'BOOKING_REVIEW_STALE','검토 후 예약·대기·일정·정원이 바뀌었습니다. 다시 검토하세요.');if((body.conflicts as string[]).length)throw new HttpError(409,'BOOKING_REVIEW_CONFLICT','확정 예약·제안·대기 충돌을 먼저 처리하세요.');if(kind==='resource'){saveResource(this.db,projectId,{...input,id:row.target_id},true);const capacity=integer(input.capacity,'변경 정원',1,10000);this.db.prepare('UPDATE platform_slots SET capacity=MIN(capacity,?) WHERE resource_id=? AND starts_at>?').run(capacity,String(row.target_id),now());this.db.prepare('UPDATE expansion_booking_rules SET capacity=MIN(capacity,?) WHERE resource_id=?').run(capacity,String(row.target_id));}else if(kind==='rule')this.saveRule(projectId,input,String(row.target_id),true);else this.saveHoliday(projectId,{...input,resourceId:row.target_id},input.remove===true,true);this.db.prepare('UPDATE advancement_booking_reviews SET applied_at=? WHERE id=?').run(now(),id);audit(this.db,'booking.review.apply',id);return this.reviewDto(one(this.db,'SELECT * FROM advancement_booking_reviews WHERE id=?',id)!);});}
  materialize(projectId: string, ruleId: string): { created: number; skipped: number } {
    const rule = one(this.db, "SELECT r.*,z.time_zone,z.disambiguation,z.gap_policy,z.revision FROM expansion_booking_rules r LEFT JOIN advancement_booking_zones z ON z.rule_id=r.id JOIN platform_resources resource ON resource.id=r.resource_id AND resource.active=1 WHERE r.id=? AND r.project_id=? AND r.enabled=1", ruleId, projectId); if (!rule) throw new HttpError(404, "BOOKING_RULE", "활성 반복 규칙과 예약 자원을 찾을 수 없습니다.");
    const days = JSON.parse(String(rule.weekdays)) as number[]; let created = 0, skipped = 0;
    transaction(this.db, () => {
      for (let clock = Date.parse(String(rule.start_date) + "T00:00:00Z"); clock <= Date.parse(String(rule.end_date) + "T00:00:00Z"); clock += 86400_000) {
        const day = new Date(clock);if(!days.includes(day.getUTCDay()))continue;const resolved=resolveWallTime({date:day.toISOString().slice(0,10),time:String(rule.start_time),timeZone:String(rule.time_zone??'UTC'),disambiguation:String(rule.disambiguation??'reject') as 'reject'|'earlier'|'later',gapPolicy:String(rule.gap_policy??'reject') as 'reject'|'shift-forward'}),startsAt=resolved.startsAt,endsAt = new Date(Date.parse(startsAt) + Number(rule.duration_minutes) * 60_000).toISOString();
        if (!days.includes(day.getUTCDay())) continue;
        if (Date.parse(startsAt) <= Date.now() || one(this.db,'SELECT 1 FROM expansion_booking_holidays WHERE project_id=? AND resource_id=? AND date=?',projectId,String(rule.resource_id),day.toISOString().slice(0,10))) { skipped++; continue; }
        const id = "recurring-" + hash(ruleId + startsAt).slice(0, 32);
        if (one(this.db, "SELECT id FROM platform_slots WHERE id=?", id)) { skipped++; continue; }
        if (one(this.db, "SELECT id FROM platform_slots WHERE resource_id=? AND starts_at<? AND ends_at>?", String(rule.resource_id), endsAt, startsAt)) throw new HttpError(409, "SLOT_OVERLAP", "반복 규칙과 기존 예약 시간이 겹칩니다.");
        this.db.prepare("INSERT INTO platform_slots VALUES(?,?,?,?,?)").run(id, String(rule.resource_id), startsAt, endsAt, Number(rule.capacity));this.db.prepare('INSERT INTO advancement_booking_slot_provenance VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,ruleId,Number(rule.revision??1),resolved.wallTime,resolved.timeZone,resolved.offsetMinutes,resolved.ambiguous?1:0,resolved.shifted?1:0,resolved.resolverVersion,process.versions.icu??'unknown',process.versions.tz??'unknown'); created++;
      } audit(this.db, "booking.recurrence.generate", ruleId);
    }); return { created, skipped };
  }
  waitlist(projectId: string, accountId?: string): SqlRow[] { return many(this.db, `SELECT id,slot_id AS slotId,account_id AS accountId,quantity,status,offer_expires_at AS offerExpiresAt,booking_id AS bookingId,created_at AS createdAt FROM expansion_booking_waitlist WHERE project_id=?${accountId ? " AND account_id=?" : ""} ORDER BY created_at LIMIT 500`, ...[projectId, ...(accountId ? [accountId] : [])]); }
  join(projectId: string, accountId: string, input: Record<string, unknown>): SqlRow {
    const slotId = text(input.slotId, "예약 시간", 100), quantity = integer(input.quantity ?? 1, "인원", 1, 10000);
    return transaction(this.db, () => {
      const slot = one(this.db, "SELECT s.* FROM platform_slots s JOIN platform_resources r ON r.id=s.resource_id WHERE s.id=? AND r.project_id=? AND r.active=1 AND s.starts_at>?", slotId, projectId, now());
      if (!slot || holiday(this.db, projectId, String(slot.resource_id), String(slot.starts_at)) || quantity > Number(slot.capacity)) throw new HttpError(400, "WAITLIST_SLOT", "대기 가능한 예약 시간을 확인하세요.");
      const old = one(this.db, "SELECT id,status,quantity FROM expansion_booking_waitlist WHERE slot_id=? AND account_id=?", slotId, accountId); if (old) { if (Number(old.quantity) !== quantity) throw new HttpError(409, "WAITLIST_QUANTITY", "동일 대기의 인원이 다릅니다."); return old; }
      const used = Number(one(this.db, "SELECT COALESCE(SUM(quantity),0) AS n FROM platform_bookings WHERE slot_id=? AND status='confirmed'", slotId)?.n ?? 0) + offered(this.db, slotId);
      if (used + quantity <= Number(slot.capacity)) throw new HttpError(409, "WAITLIST_AVAILABLE", "현재 예약할 수 있습니다. 예약 신청을 이용하세요.");
      const id = randomUUID(); this.db.prepare("INSERT INTO expansion_booking_waitlist VALUES(?,?,?, ?,?,'waiting',NULL,NULL,NULL,?)").run(id, projectId, slotId, accountId, quantity, now()); return one(this.db, "SELECT id,status,quantity FROM expansion_booking_waitlist WHERE id=?", id)!;
    });
  }
  offer(projectId: string): { offered: number; expired: number } {
    return transaction(this.db, () => {
      const expired = Number(this.db.prepare("UPDATE expansion_booking_waitlist SET status='expired',offer_token_hash=NULL WHERE project_id=? AND status='offered' AND offer_expires_at<=?").run(projectId, Date.now()).changes); let count = 0;
      for (const entry of many(this.db, "SELECT w.*,s.resource_id,s.starts_at,s.capacity FROM expansion_booking_waitlist w JOIN platform_slots s ON s.id=w.slot_id JOIN platform_resources r ON r.id=s.resource_id WHERE w.project_id=? AND w.status='waiting' AND s.starts_at>? AND r.active=1 ORDER BY w.created_at,w.id LIMIT 100", projectId, now())) {
        if (holiday(this.db, projectId, String(entry.resource_id), String(entry.starts_at))) continue;
        const used = Number(one(this.db, "SELECT COALESCE(SUM(quantity),0) AS n FROM platform_bookings WHERE slot_id=? AND status='confirmed'", String(entry.slot_id))?.n ?? 0) + offered(this.db, String(entry.slot_id));
        if (used + Number(entry.quantity) > Number(entry.capacity)) continue;
        this.db.prepare("UPDATE expansion_booking_waitlist SET status='offered',offer_expires_at=? WHERE id=? AND status='waiting'").run(Date.now() + 600_000, String(entry.id)); count++;
      } return { offered: count, expired };
    });
  }
  accept(projectId: string, accountId: string, id: string): SqlRow {
    return transaction(this.db, () => {
      const entry = one(this.db, "SELECT * FROM expansion_booking_waitlist WHERE id=? AND project_id=? AND account_id=?", id, projectId, accountId);
      if (!entry) throw new HttpError(404, "WAITLIST", "대기를 찾을 수 없습니다."); if (entry.status === "accepted") return one(this.db, "SELECT * FROM platform_bookings WHERE id=?", String(entry.booking_id))!;
      if (entry.status !== "offered" || Number(entry.offer_expires_at) <= Date.now()) throw new HttpError(409, "WAITLIST_EXPIRED", "대기 제안이 만료되었거나 아직 제공되지 않았습니다.");
      const slot = one(this.db, "SELECT s.* FROM platform_slots s JOIN platform_resources r ON r.id=s.resource_id WHERE s.id=? AND r.active=1 AND s.starts_at>?", String(entry.slot_id), now()); if (!slot || holiday(this.db, projectId, String(slot.resource_id), String(slot.starts_at))) throw new HttpError(409, "WAITLIST_SLOT", "예약 시간을 사용할 수 없습니다.");
      const used = Number(one(this.db, "SELECT COALESCE(SUM(quantity),0) AS n FROM platform_bookings WHERE slot_id=? AND status='confirmed'", String(entry.slot_id))?.n ?? 0) + offered(this.db, String(entry.slot_id)); if (used > Number(slot.capacity)) throw new HttpError(409, "BOOKING_FULL", "예약 정원이 변경되었습니다.");
      consumeUsage(this.db, projectId, "bookings"); const bookingId = randomUUID(), fingerprint = hash(JSON.stringify({ slotId: entry.slot_id, quantity: entry.quantity }));
      this.db.prepare("INSERT INTO platform_bookings VALUES(?,?,?,?,?,'confirmed',?,?,?)").run(bookingId, projectId, String(entry.slot_id), accountId, Number(entry.quantity), "waitlist-" + id, fingerprint, now());
      recordPlatformEvent(this.db, projectId, "booking.created", bookingId, { id: bookingId, bookingId, slotId: entry.slot_id, quantity: entry.quantity });
      this.db.prepare("UPDATE expansion_booking_waitlist SET status='accepted',booking_id=? WHERE id=?").run(bookingId, id); audit(this.db, "booking.waitlist.accept", id); return one(this.db, "SELECT * FROM platform_bookings WHERE id=?", bookingId)!;
    });
  }
  cancel(projectId: string, accountId: string, id: string): void { const result = this.db.prepare("UPDATE expansion_booking_waitlist SET status='cancelled' WHERE id=? AND project_id=? AND account_id=? AND status IN('waiting','offered')").run(id, projectId, accountId); if (!result.changes) throw new HttpError(409, "WAITLIST", "대기를 취소할 수 없습니다."); }
  fulfillments(projectId: string): OrderFulfillment[] { return many(this.db, "SELECT * FROM expansion_order_fulfillments WHERE project_id=? ORDER BY updated_at DESC LIMIT 200", projectId).map(row => ({ orderId: String(row.order_id), projectId: String(row.project_id), status: String(row.status) as OrderFulfillment["status"], tracking: String(row.tracking), notes: String(row.notes), updatedBy: String(row.updated_by), updatedAt: String(row.updated_at) })); }
  fulfill(projectId: string, actor: string, id: string, input: Record<string, unknown>): OrderFulfillment {
    assertFinancialReady(this.db, id);
    const order = one(this.db, "SELECT status FROM platform_orders WHERE id=? AND project_id=?", id, projectId), status = input.status;
    if (!order) throw new HttpError(404, "ORDER", "주문을 찾을 수 없습니다.");
    if (!["unfulfilled", "processing", "fulfilled", "returned"].includes(String(status)) || ["processing", "fulfilled"].includes(String(status)) && !["paid", "partially_refunded"].includes(String(order.status))) throw new HttpError(409, "FULFILLMENT_STATE", "서버에서 결제가 확인된 주문만 후처리할 수 있습니다.");
    this.db.prepare("INSERT INTO expansion_order_fulfillments VALUES(?,?,?,?,?,?,?) ON CONFLICT(order_id) DO UPDATE SET status=excluded.status,tracking=excluded.tracking,notes=excluded.notes,updated_by=excluded.updated_by,updated_at=excluded.updated_at").run(id, projectId, String(status), text(input.tracking ?? "", "송장", 200, true), text(input.notes ?? "", "후처리 메모", 2000, true), actor, now()); audit(this.db, "order.fulfill", id); return this.fulfillments(projectId).find(item => item.orderId === id)!;
  }
}
