export const EXPANSION_BUSINESS_MIGRATION = `
CREATE TABLE IF NOT EXISTS expansion_revision_snapshots(project_id TEXT NOT NULL REFERENCES expansion_project_scopes(project_id),revision INTEGER NOT NULL,body TEXT NOT NULL CHECK(json_valid(body)),fingerprint TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(project_id,revision));
CREATE TABLE IF NOT EXISTS expansion_booking_rules(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,resource_id TEXT NOT NULL,name TEXT NOT NULL,start_date TEXT NOT NULL,end_date TEXT NOT NULL,weekdays TEXT NOT NULL CHECK(json_valid(weekdays)),start_time TEXT NOT NULL,duration_minutes INTEGER NOT NULL CHECK(duration_minutes>0),capacity INTEGER NOT NULL CHECK(capacity>0),enabled INTEGER NOT NULL CHECK(enabled IN(0,1)),created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS expansion_booking_holidays(project_id TEXT NOT NULL,resource_id TEXT NOT NULL,date TEXT NOT NULL,reason TEXT NOT NULL,PRIMARY KEY(project_id,resource_id,date));
CREATE TABLE IF NOT EXISTS expansion_booking_waitlist(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,slot_id TEXT NOT NULL,account_id TEXT NOT NULL,quantity INTEGER NOT NULL CHECK(quantity>0),status TEXT NOT NULL CHECK(status IN('waiting','offered','accepted','cancelled','expired')),offer_token_hash TEXT UNIQUE,offer_expires_at INTEGER,booking_id TEXT,created_at TEXT NOT NULL,UNIQUE(slot_id,account_id));
CREATE TABLE IF NOT EXISTS expansion_order_fulfillments(order_id TEXT PRIMARY KEY,project_id TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN('unfulfilled','processing','fulfilled','returned')),tracking TEXT NOT NULL,notes TEXT NOT NULL,updated_by TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS expansion_webhook_events(id TEXT PRIMARY KEY,credential_id TEXT NOT NULL REFERENCES expansion_credentials(id),event_id TEXT NOT NULL,fingerprint TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN('pending','completed')),created_at TEXT NOT NULL,UNIQUE(credential_id,event_id));
CREATE TABLE IF NOT EXISTS expansion_content_authors(project_id TEXT NOT NULL,collection_id TEXT NOT NULL,record_id TEXT NOT NULL,content_revision INTEGER NOT NULL,submitted_by TEXT NOT NULL,approved_by TEXT,PRIMARY KEY(project_id,collection_id,record_id,content_revision));
`;
