import {spawn} from 'node:child_process';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {sourceIdentity} from './source-identity.mjs';
const root=process.cwd(),startedSourceHash=sourceIdentity(root).hash,folder=path.join(root,'.data/system-verification');await mkdir(folder,{recursive:true});
const npmCli=process.env.npm_execpath;if(!npmCli)throw new Error('Run npm run verify:system');
const checks=[['typecheck',['run','typecheck']],['lint',['run','lint']],['test',['test']],['build',['run','build']],['browser',['run','test:e2e']],['delivery',['run','verify:delivery']],['capacity',['run','system:benchmark','--','--seconds','10','--records','10000']],['drills',['run','system:drill']],['audit',['audit','--audit-level=high']]] as const;
const results:{id:string;status:'passed'|'failed';exitCode:number;durationMs:number;log:string}[]=[];
for(const [id,args] of checks){const started=Date.now(),chunks:Buffer[]=[];const exitCode=await new Promise<number>((resolve,reject)=>{const child=spawn(process.execPath,[npmCli,...args],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe']});child.stdout.on('data',(chunk:Buffer)=>chunks.push(chunk));child.stderr.on('data',(chunk:Buffer)=>chunks.push(chunk));child.once('error',reject);child.once('exit',code=>resolve(code??1));});const log=path.join(folder,id+'.log');await writeFile(log,Buffer.concat(chunks));results.push({id,status:exitCode===0?'passed':'failed',exitCode,durationMs:Date.now()-started,log:path.relative(root,log).replaceAll('\\','/')});console.log(JSON.stringify(results.at(-1)));}
const build=JSON.parse(await readFile(path.join(root,'dist-service/build.json'),'utf8')) as {hash:string;commit:string|null};const matrix=JSON.parse(await readFile(path.join(root,'docs/system-evidence-matrix.json'),'utf8')) as {id:string;code:string[];tests:string[];external:string[]}[];for(const item of matrix)for(const file of [...item.code,...item.tests])if(file.includes('/'))await readFile(path.join(root,file));
const finalSourceHash=sourceIdentity(root).hash,sourceStable=startedSourceHash===finalSourceHash&&build.hash===finalSourceHash;if(matrix.length!==48||matrix.some((item,index)=>item.id!=='H'+String(index+1).padStart(2,'0')))throw new Error('Expected the complete ordered H01-H48 evidence matrix');const passed=sourceStable&&results.every(item=>item.status==='passed'),evidence={format:1,createdAt:new Date().toISOString(),sourceHash:finalSourceHash,startedSourceHash,sourceStable,buildHash:build.hash,buildCommit:build.commit,host:{platform:process.platform,arch:process.arch,node:process.versions.node,cpu:os.cpus()[0]?.model,logicalCpus:os.cpus().length,memoryBytes:os.totalmem()},passed,checks:results,requirements:matrix.map(item=>({...item,status:passed?(item.external.length?'local-checks-passed-external-conditional':'local-checks-passed'):'verification-incomplete'})),boundaries:{productionDeployment:'not-configured',realProviders:'not-configured',multiHost:'not-tested',physicalDevices:'not-tested',screenReader:'not-tested',otherOperatingSystems:'not-tested'}};await writeFile(path.join(root,'.data/system-verification.json'),JSON.stringify(evidence,null,2));console.log(JSON.stringify({passed,report:'.data/system-verification.json',requirements:matrix.length}));process.exitCode=passed?0:1;
