CREATE TABLE IF NOT EXISTS advancement_mfa(account_id TEXT PRIMARY KEY REFERENCES creator_accounts(id),secret TEXT,pending_secret TEXT,pending_until INTEGER NOT NULL DEFAULT 0,last_counter INTEGER NOT NULL DEFAULT -1,recovery_hashes TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(recovery_hashes)),enrolled_at TEXT,failures INTEGER NOT NULL DEFAULT 0,reset_at INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS advancement_step_up(token_hash TEXT PRIMARY KEY,account_id TEXT NOT NULL,session_id TEXT NOT NULL,method TEXT NOT NULL,path TEXT NOT NULL,scope_key TEXT NOT NULL,fingerprint TEXT NOT NULL,expires_at INTEGER NOT NULL,used_at TEXT);
CREATE TABLE IF NOT EXISTS advancement_service_identities(id TEXT PRIMARY KEY,name TEXT NOT NULL,scope TEXT NOT NULL CHECK(json_valid(scope)),capabilities TEXT NOT NULL CHECK(json_valid(capabilities)),owner_id TEXT NOT NULL,expires_at INTEGER NOT NULL,revoked INTEGER NOT NULL CHECK(revoked IN(0,1)),revision INTEGER NOT NULL,last_used_at TEXT);
CREATE TABLE IF NOT EXISTS advancement_service_keys(id TEXT PRIMARY KEY,identity_id TEXT NOT NULL REFERENCES advancement_service_identities(id),token_hash TEXT NOT NULL UNIQUE,expires_at INTEGER NOT NULL,revoked INTEGER NOT NULL DEFAULT 0 CHECK(revoked IN(0,1)),created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS advancement_secret_versions(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,workspace_id TEXT NOT NULL,project_id TEXT NOT NULL,environment_id TEXT NOT NULL,name TEXT NOT NULL,version INTEGER NOT NULL,ciphertext TEXT NOT NULL,key_id TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN('registered','tested','active','retired')),tested_at TEXT,created_at TEXT NOT NULL,UNIQUE(environment_id,name,version));
CREATE UNIQUE INDEX IF NOT EXISTS advancement_secret_active ON advancement_secret_versions(environment_id,name) WHERE status='active';
CREATE TABLE IF NOT EXISTS advancement_key_rotation(id TEXT PRIMARY KEY,target_key_id TEXT NOT NULL,status TEXT NOT NULL,processed INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS advancement_support_sessions(id TEXT PRIMARY KEY,scope TEXT NOT NULL CHECK(json_valid(scope)),support_id TEXT NOT NULL,approved_by TEXT NOT NULL,capabilities TEXT NOT NULL CHECK(json_valid(capabilities)),reason TEXT NOT NULL,expires_at INTEGER NOT NULL,revoked INTEGER NOT NULL DEFAULT 0 CHECK(revoked IN(0,1)),created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS advancement_auth_tombstones(kind TEXT NOT NULL,resource_id TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(kind,resource_id));
